<?php
namespace AppBundle\DataFixtures\ORM;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use AppBundle\Entity\Categoria;
class Categorias implements FixtureInterface
{
	public function load(ObjectManager $manager)
	{
		$categorias = array(
			array('id' => '9','nombre' => 'Abogados','idPadre' => '1'),
			array('id' => '10','nombre' => 'Asesorías','idPadre' => '1'),
			array('id' => '11','nombre' => 'Academias','idPadre' => '1'),
			array('id' => '12','nombre' => 'Agricultura','idPadre' => '1'),
			array('id' => '13','nombre' => 'Alimentación','idPadre' => '1'),
			array('id' => '14','nombre' => 'Animales','idPadre' => '1'),
			array('id' => '15','nombre' => 'Asociaciones','idPadre' => '1'),
			array('id' => '16','nombre' => 'Bodas','idPadre' => '1'),
			array('id' => '17','nombre' => 'Carpintería','idPadre' => '1'),
			array('id' => '18','nombre' => 'Comercio','idPadre' => '1'),
			array('id' => '19','nombre' => 'Construcción y Reformas','idPadre' => '1'),
			array('id' => '20','nombre' => 'Consultoría','idPadre' => '1'),
			array('id' => '21','nombre' => 'Deportes','idPadre' => '1'),
			array('id' => '22','nombre' => 'Electricistas','idPadre' => '1'),
			array('id' => '23','nombre' => 'Estética y Belleza','idPadre' => '1'),
			array('id' => '24','nombre' => 'Ganadería','idPadre' => '1'),
			array('id' => '25','nombre' => 'Hogar y Decoración','idPadre' => '1'),
			array('id' => '26','nombre' => 'Hoteles','idPadre' => '1'),
			array('id' => '27','nombre' => 'Ingeniería','idPadre' => '1'),
			array('id' => '28','nombre' => 'Infantil','idPadre' => '1'),
			array('id' => '29','nombre' => 'Informática','idPadre' => '1'),
			array('id' => '31','nombre' => 'Inmobiliarias y Pisos','idPadre' => '1'),
			array('id' => '32','nombre' => 'Jardinería','idPadre' => '1'),
			array('id' => '33','nombre' => 'Limpieza','idPadre' => '1'),
			array('id' => '34','nombre' => 'Mantenimiento','idPadre' => '1'),
			array('id' => '35','nombre' => 'Medicina y Salud','idPadre' => '1'),
			array('id' => '36','nombre' => 'Moda','idPadre' => '1'),
			array('id' => '37','nombre' => 'Ocio y Tiempo Libre','idPadre' => '1'),
			array('id' => '38','nombre' => 'Publicidad y Eventos','idPadre' => '1'),
			array('id' => '370','nombre' => 'Artesanía','idPadre' => '1'),
			array('id' => '502','nombre' => 'Restaurantes','idPadre' => '1'),
			array('id' => '503','nombre' => 'Seguridad','idPadre' => '1'),
			array('id' => '504','nombre' => 'Seguros y Tasaciones','idPadre' => '1'),
			array('id' => '505','nombre' => 'Transportes','idPadre' => '1'),
			array('id' => '506','nombre' => 'Vehículos','idPadre' => '1'),
			array('id' => '507','nombre' => 'Viajes','idPadre' => '1'),
			array('id' => '510','nombre' => 'Abogado Civil','idPadre' => '9'),
			array('id' => '511','nombre' => 'Abogado Laboral','idPadre' => '9'),
			array('id' => '512','nombre' => 'Abogado Mercantil','idPadre' => '9'),
			array('id' => '513','nombre' => 'Abogado Penal','idPadre' => '9'),
			array('id' => '514','nombre' => 'Despacho de Abogados','idPadre' => '9'),
			array('id' => '515','nombre' => 'Divorcios','idPadre' => '9'),
			array('id' => '517','nombre' => 'Administrador de Fincas','idPadre' => '10'),
			array('id' => '518','nombre' => 'Asesores Empresas','idPadre' => '10'),
			array('id' => '519','nombre' => 'Asesoría Mercantil','idPadre' => '10'),
			array('id' => '520','nombre' => 'Asesoría Fiscal','idPadre' => '10'),
			array('id' => '521','nombre' => 'Asesoría Recursos Humanos','idPadre' => '10'),
			array('id' => '522','nombre' => 'Auditoría de Cuentas','idPadre' => '10'),
			array('id' => '523','nombre' => 'Financieras (EAFI)','idPadre' => '10'),
			array('id' => '524','nombre' => 'Gestorías','idPadre' => '10'),
			array('id' => '525','nombre' => 'Notario','idPadre' => '10'),
			array('id' => '526','nombre' => 'Procurador','idPadre' => '10'),
			array('id' => '527','nombre' => 'Servicios Jurídicos','idPadre' => '10'),
			array('id' => '528','nombre' => 'Academias de Corte y Confección','idPadre' => '11'),
			array('id' => '529','nombre' => 'Academias de Dibujo y Pintura','idPadre' => '11'),
			array('id' => '530','nombre' => 'Academias de Baile','idPadre' => '11'),
			array('id' => '531','nombre' => 'Academias de Formación','idPadre' => '11'),
			array('id' => '532','nombre' => 'Academias de Idiomas','idPadre' => '11'),
			array('id' => '533','nombre' => 'Academias de Inglés','idPadre' => '11'),
			array('id' => '534','nombre' => 'Academias de Informática','idPadre' => '11'),
			array('id' => '535','nombre' => 'Academias de Oposiciones','idPadre' => '11'),
			array('id' => '536','nombre' => 'Academias Online','idPadre' => '11'),
			array('id' => '537','nombre' => 'Autoescuelas','idPadre' => '11'),
			array('id' => '538','nombre' => 'Escuelas Artesanas','idPadre' => '11'),
			array('id' => '539','nombre' => 'Escuela Oficial de Idiomas','idPadre' => '11'),
			array('id' => '540','nombre' => 'Escuela de Hostelería','idPadre' => '11'),
			array('id' => '541','nombre' => 'Escuela de Cocina','idPadre' => '11'),
			array('id' => '542','nombre' => 'Facultades y Universidades','idPadre' => '11'),
			array('id' => '543','nombre' => 'Profesor particular','idPadre' => '11'),
			array('id' => '544','nombre' => 'Abono Orgánico','idPadre' => '12'),
			array('id' => '545','nombre' => 'Alimento para Ganado','idPadre' => '12'),
			array('id' => '546','nombre' => 'Asociaciones Agrarias','idPadre' => '12'),
			array('id' => '547','nombre' => 'Avicultores','idPadre' => '12'),
			array('id' => '548','nombre' => 'Bodegas Vinícolas','idPadre' => '12'),
			array('id' => '549','nombre' => 'Construcción Agrícola','idPadre' => '12'),
			array('id' => '550','nombre' => 'Hortalizas','idPadre' => '12'),
			array('id' => '551','nombre' => 'Instalaciones de Riego','idPadre' => '12'),
			array('id' => '552','nombre' => 'Maquinaria Agrícola','idPadre' => '12'),
			array('id' => '553','nombre' => 'Pesticidas','idPadre' => '12'),
			array('id' => '554','nombre' => 'Piensos','idPadre' => '12'),
			array('id' => '555','nombre' => 'Productos Agropecuarios','idPadre' => '12'),
			array('id' => '556','nombre' => 'Semilleros','idPadre' => '12'),
			array('id' => '557','nombre' => 'Tratamiento de Agua','idPadre' => '12'),
			array('id' => '558','nombre' => 'Viveros','idPadre' => '12'),
			array('id' => '559','nombre' => 'Zumos y Cítricos','idPadre' => '12'),
			array('id' => '560','nombre' => 'Aperitivos','idPadre' => '13'),
			array('id' => '561','nombre' => 'Almacén de Comestibles','idPadre' => '13'),
			array('id' => '562','nombre' => 'Café','idPadre' => '13'),
			array('id' => '563','nombre' => 'Carnicerías','idPadre' => '13'),
			array('id' => '564','nombre' => 'Cereales','idPadre' => '13'),
			array('id' => '565','nombre' => 'Comida para llevar','idPadre' => '13'),
			array('id' => '566','nombre' => 'Congelados','idPadre' => '13'),
			array('id' => '567','nombre' => 'Conservas','idPadre' => '13'),
			array('id' => '568','nombre' => 'Dietistas','idPadre' => '13'),
			array('id' => '569','nombre' => 'Distribuidoras de Alimentos','idPadre' => '13'),
			array('id' => '570','nombre' => 'Dulces','idPadre' => '13'),
			array('id' => '571','nombre' => 'Embasadoras','idPadre' => '13'),
			array('id' => '572','nombre' => 'Frutos Secos','idPadre' => '13'),
			array('id' => '573','nombre' => 'Panaderías','idPadre' => '13'),
			array('id' => '574','nombre' => 'Pastelerías','idPadre' => '13'),
			array('id' => '575','nombre' => 'Pescaderías','idPadre' => '13'),
			array('id' => '576','nombre' => 'Mercados de Alimentación','idPadre' => '13'),
			array('id' => '577','nombre' => 'Vinaterías','idPadre' => '13'),
			array('id' => '578','nombre' => 'Animales Domésticos','idPadre' => '14'),
			array('id' => '579','nombre' => 'Adiestradores de Animales','idPadre' => '14'),
			array('id' => '580','nombre' => 'Acuarios','idPadre' => '14'),
			array('id' => '581','nombre' => 'Clínicas Veterinarias','idPadre' => '14'),
			array('id' => '582','nombre' => 'Criaderos','idPadre' => '14'),
			array('id' => '583','nombre' => 'Mascotas','idPadre' => '14'),
			array('id' => '584','nombre' => 'Pajarerías','idPadre' => '14'),
			array('id' => '585','nombre' => 'Peluquería Canina','idPadre' => '14'),
			array('id' => '586','nombre' => 'Residencias de Animales','idPadre' => '14'),
			array('id' => '587','nombre' => 'Tiendas de Animales','idPadre' => '14'),
			array('id' => '588','nombre' => 'Alfareros','idPadre' => '370'),
			array('id' => '589','nombre' => 'Artesanos Madera','idPadre' => '370'),
			array('id' => '590','nombre' => 'Artesanos Piedra','idPadre' => '370'),
			array('id' => '591','nombre' => 'Artesanos Vidrio','idPadre' => '370'),
			array('id' => '592','nombre' => 'Asociaciones Artesanas','idPadre' => '370'),
			array('id' => '593','nombre' => 'Bisutería Artesanal','idPadre' => '370'),
			array('id' => '594','nombre' => 'Cerámica','idPadre' => '370'),
			array('id' => '595','nombre' => 'Cuero Artesano','idPadre' => '370'),
			array('id' => '596','nombre' => 'Escuelas Artesanas','idPadre' => '370'),
			array('id' => '597','nombre' => 'Forja Artesanal','idPadre' => '370'),
			array('id' => '598','nombre' => 'Maestros Artesanos','idPadre' => '370'),
			array('id' => '599','nombre' => 'Marroquinería','idPadre' => '370'),
			array('id' => '600','nombre' => 'Modistas Artesanos','idPadre' => '370'),
			array('id' => '601','nombre' => 'Muebles Artesanos','idPadre' => '370'),
			array('id' => '602','nombre' => 'Orfebrería','idPadre' => '370'),
			array('id' => '603','nombre' => 'Productos Artesanos','idPadre' => '370'),
			array('id' => '604','nombre' => 'Restauración','idPadre' => '370'),
			array('id' => '605','nombre' => 'Regalos Artesanos','idPadre' => '370'),
			array('id' => '606','nombre' => 'Taller Artesano','idPadre' => '370'),
			array('id' => '607','nombre' => 'Tiendas de Artesanía','idPadre' => '370'),
			array('id' => '608','nombre' => 'Asociaciones Agrarias','idPadre' => '15'),
			array('id' => '609','nombre' => 'Asociaciones Deportivas','idPadre' => '15'),
			array('id' => '610','nombre' => 'Asociaciones Hosteleras','idPadre' => '15'),
			array('id' => '611','nombre' => 'Asociaciones Profesionales','idPadre' => '15'),
			array('id' => '612','nombre' => 'Asociaciones Sindicales','idPadre' => '15'),
			array('id' => '613','nombre' => 'Asociaciones Tercera Edad','idPadre' => '15'),
			array('id' => '614','nombre' => 'Decoración de Boda','idPadre' => '16'),
			array('id' => '615','nombre' => 'Despedidas de Soltero/a','idPadre' => '16'),
			array('id' => '616','nombre' => 'Empresas de Bodas','idPadre' => '16'),
			array('id' => '617','nombre' => 'Fotógrafos de Boda','idPadre' => '16'),
			array('id' => '618','nombre' => 'Invitaciones de Boda','idPadre' => '16'),
			array('id' => '619','nombre' => 'Listas de Boda','idPadre' => '16'),
			array('id' => '620','nombre' => 'Regalos de Boda','idPadre' => '16'),
			array('id' => '621','nombre' => 'Salones de Boda','idPadre' => '16'),
			array('id' => '622','nombre' => 'Trajes de Boda','idPadre' => '16'),
			array('id' => '623','nombre' => 'Viajes Luna de Miel','idPadre' => '16'),
			array('id' => '624','nombre' => 'Almacén de Madera','idPadre' => '17'),
			array('id' => '625','nombre' => 'Bricolage','idPadre' => '17'),
			array('id' => '626','nombre' => 'Carpinteros','idPadre' => '17'),
			array('id' => '627','nombre' => 'Carpintería de Aluminio','idPadre' => '17'),
			array('id' => '628','nombre' => 'Carpintería de Madera','idPadre' => '17'),
			array('id' => '629','nombre' => 'Carpintería Metálica','idPadre' => '17'),
			array('id' => '630','nombre' => 'Carpintería PVC','idPadre' => '17'),
			array('id' => '631','nombre' => 'Cerramientos Metálicos','idPadre' => '17'),
			array('id' => '632','nombre' => 'Ebanistas','idPadre' => '17'),
			array('id' => '633','nombre' => 'Fabricación de Muebles','idPadre' => '17'),
			array('id' => '634','nombre' => 'Herramientas de Carpintería','idPadre' => '17'),
			array('id' => '635','nombre' => 'Antigüedades','idPadre' => '18'),
			array('id' => '636','nombre' => 'Comercio Exterior','idPadre' => '18'),
			array('id' => '637','nombre' => 'Colchonerías','idPadre' => '18'),
			array('id' => '638','nombre' => 'Droguerías','idPadre' => '18'),
			array('id' => '639','nombre' => 'Enmarcaciones','idPadre' => '18'),
			array('id' => '640','nombre' => 'Estaciones de Servicio','idPadre' => '18'),
			array('id' => '641','nombre' => 'Estancos','idPadre' => '18'),
			array('id' => '642','nombre' => 'Ferreterías','idPadre' => '18'),
			array('id' => '643','nombre' => 'Floristerías','idPadre' => '18'),
			array('id' => '644','nombre' => 'Joyerías','idPadre' => '18'),
			array('id' => '645','nombre' => 'Lencería','idPadre' => '18'),
			array('id' => '646','nombre' => 'Perfumerías','idPadre' => '18'),
			array('id' => '647','nombre' => 'Regalos','idPadre' => '18'),
			array('id' => '648','nombre' => 'Zapaterías','idPadre' => '18'),
			array('id' => '649','nombre' => 'Aislamientos','idPadre' => '19'),
			array('id' => '650','nombre' => 'Albañiles','idPadre' => '19'),
			array('id' => '651','nombre' => 'Alicatadores','idPadre' => '19'),
			array('id' => '652','nombre' => 'Alquiler de Maquinaria','idPadre' => '19'),
			array('id' => '653','nombre' => 'Aparejadores','idPadre' => '19'),
			array('id' => '654','nombre' => 'Arquitectos','idPadre' => '19'),
			array('id' => '655','nombre' => 'Calefacción','idPadre' => '19'),
			array('id' => '656','nombre' => 'Constructoras','idPadre' => '19'),
			array('id' => '657','nombre' => 'Contratistas','idPadre' => '19'),
			array('id' => '658','nombre' => 'Cubiertas','idPadre' => '19'),
			array('id' => '659','nombre' => 'Domótica','idPadre' => '19'),
			array('id' => '660','nombre' => 'Escayolistas','idPadre' => '19'),
			array('id' => '661','nombre' => 'Electricistas','idPadre' => '19'),
			array('id' => '662','nombre' => 'Excavaciones','idPadre' => '19'),
			array('id' => '663','nombre' => 'Ferrallistas','idPadre' => '19'),
			array('id' => '664','nombre' => 'Fontaneros','idPadre' => '19'),
			array('id' => '665','nombre' => 'Grúas','idPadre' => '19'),
			array('id' => '666','nombre' => 'Hormigón','idPadre' => '19'),
			array('id' => '667','nombre' => 'Iluminación','idPadre' => '19'),
			array('id' => '668','nombre' => 'Materiales de Construcción','idPadre' => '19'),
			array('id' => '669','nombre' => 'Obra Pública','idPadre' => '19'),
			array('id' => '670','nombre' => 'Reformas','idPadre' => '19'),
			array('id' => '671','nombre' => 'Revestimientos','idPadre' => '19'),
			array('id' => '672','nombre' => 'Piscinas','idPadre' => '19'),
			array('id' => '673','nombre' => 'Pintores','idPadre' => '19'),
			array('id' => '674','nombre' => 'Saneamientos','idPadre' => '19'),
			array('id' => '675','nombre' => 'Consultora Empresarial','idPadre' => '20'),
			array('id' => '676','nombre' => 'Consultora de Empleo','idPadre' => '20'),
			array('id' => '677','nombre' => 'Consultora Recursos Humanos','idPadre' => '20'),
			array('id' => '678','nombre' => 'Consultora Tecnológica','idPadre' => '20'),
			array('id' => '679','nombre' => 'Consultoría Energética','idPadre' => '20'),
			array('id' => '680','nombre' => 'Consultoría Energías Renovables','idPadre' => '20'),
			array('id' => '681','nombre' => 'Consultoría Calidad','idPadre' => '20'),
			array('id' => '682','nombre' => 'Consultoría Integral','idPadre' => '20'),
			array('id' => '683','nombre' => 'Consultoría Jurídica','idPadre' => '20'),
			array('id' => '684','nombre' => 'Consultora Medioambiental','idPadre' => '20'),
			array('id' => '685','nombre' => 'Consultoría de Negocio','idPadre' => '20'),
			array('id' => '686','nombre' => 'Protección de Datos','idPadre' => '20'),
			array('id' => '687','nombre' => 'Asociaciones Deportivas','idPadre' => '21'),
			array('id' => '688','nombre' => 'Centro Deportivo','idPadre' => '21'),
			array('id' => '689','nombre' => 'Deportes de Aventura','idPadre' => '21'),
			array('id' => '690','nombre' => 'Entrenador Personal','idPadre' => '21'),
			array('id' => '691','nombre' => 'Fitness','idPadre' => '21'),
			array('id' => '692','nombre' => 'Gimnasios','idPadre' => '21'),
			array('id' => '693','nombre' => 'Natación','idPadre' => '21'),
			array('id' => '694','nombre' => 'Outlet Deportes','idPadre' => '21'),
			array('id' => '695','nombre' => 'Ropa Deportiva','idPadre' => '21'),
			array('id' => '696','nombre' => 'Tiendas de Deportes','idPadre' => '21'),
			array('id' => '697','nombre' => 'Electricista a domicilio','idPadre' => '22'),
			array('id' => '698','nombre' => 'Iluminación','idPadre' => '22'),
			array('id' => '699','nombre' => 'Instalador Eléctrico','idPadre' => '22'),
			array('id' => '700','nombre' => 'Reparación Eléctrica','idPadre' => '22'),
			array('id' => '701','nombre' => 'Instalador Autorizado','idPadre' => '22'),
			array('id' => '702','nombre' => 'Adelgazar','idPadre' => '23'),
			array('id' => '703','nombre' => 'Cirugía Estética','idPadre' => '23'),
			array('id' => '704','nombre' => 'Cosmética','idPadre' => '23'),
			array('id' => '705','nombre' => 'Depilación','idPadre' => '23'),
			array('id' => '706','nombre' => 'Manicura','idPadre' => '23'),
			array('id' => '707','nombre' => 'Masajes','idPadre' => '23'),
			array('id' => '708','nombre' => 'Mesoterapia','idPadre' => '23'),
			array('id' => '709','nombre' => 'Peluquería','idPadre' => '23'),
			array('id' => '710','nombre' => 'Productos Estéticos','idPadre' => '23'),
			array('id' => '711','nombre' => 'Rayos uva','idPadre' => '23'),
			array('id' => '712','nombre' => 'Pilates','idPadre' => '23'),
			array('id' => '713','nombre' => 'Solarium','idPadre' => '23'),
			array('id' => '714','nombre' => 'Spa','idPadre' => '23'),
			array('id' => '715','nombre' => 'Tatuajes','idPadre' => '23'),
			array('id' => '716','nombre' => 'Tratamientos Capilares','idPadre' => '23'),
			array('id' => '717','nombre' => 'Alimento ganado','idPadre' => '24'),
			array('id' => '718','nombre' => 'Explotación ganadera','idPadre' => '24'),
			array('id' => '719','nombre' => 'Ganado','idPadre' => '24'),
			array('id' => '720','nombre' => 'Ganadería ecológica','idPadre' => '24'),
			array('id' => '721','nombre' => 'Ganadería intensiva','idPadre' => '24'),
			array('id' => '722','nombre' => 'Caballos','idPadre' => '24'),
			array('id' => '723','nombre' => 'Ganadería caprina','idPadre' => '24'),
			array('id' => '724','nombre' => 'Ganadería bovina','idPadre' => '24'),
			array('id' => '725','nombre' => 'Ganadería vacuna','idPadre' => '24'),
			array('id' => '726','nombre' => 'Ganadería porcina','idPadre' => '24'),
			array('id' => '727','nombre' => 'Toros','idPadre' => '24'),
			array('id' => '728','nombre' => 'Alfombras','idPadre' => '25'),
			array('id' => '729','nombre' => 'Cocinas','idPadre' => '25'),
			array('id' => '730','nombre' => 'Decorador de Interiores','idPadre' => '25'),
			array('id' => '731','nombre' => 'Decoración de Baños','idPadre' => '25'),
			array('id' => '732','nombre' => 'Decoración de Jardines','idPadre' => '25'),
			array('id' => '733','nombre' => 'Domótica','idPadre' => '25'),
			array('id' => '734','nombre' => 'Diseño de Oficinas','idPadre' => '25'),
			array('id' => '735','nombre' => 'Enmarcación','idPadre' => '25'),
			array('id' => '736','nombre' => 'Flores Artificiales','idPadre' => '25'),
			array('id' => '737','nombre' => 'Lámparas','idPadre' => '25'),
			array('id' => '738','nombre' => 'Mobiliario Antiguo','idPadre' => '25'),
			array('id' => '739','nombre' => 'Tapiceros','idPadre' => '25'),
			array('id' => '740','nombre' => 'Tiendas de Decoración','idPadre' => '25'),
			array('id' => '741','nombre' => 'Persianas y Toldos','idPadre' => '25'),
			array('id' => '742','nombre' => 'Albergues','idPadre' => '26'),
			array('id' => '743','nombre' => 'Apartahoteles','idPadre' => '26'),
			array('id' => '744','nombre' => 'Apartamentos','idPadre' => '26'),
			array('id' => '745','nombre' => 'Balnearios','idPadre' => '26'),
			array('id' => '746','nombre' => 'Bungalow','idPadre' => '26'),
			array('id' => '747','nombre' => 'Camping','idPadre' => '26'),
			array('id' => '748','nombre' => 'Casas Rurales','idPadre' => '26'),
			array('id' => '749','nombre' => 'Hospedería','idPadre' => '26'),
			array('id' => '750','nombre' => 'Hoteles Rurales','idPadre' => '26'),
			array('id' => '751','nombre' => 'Moteles','idPadre' => '26'),
			array('id' => '752','nombre' => 'Paradores','idPadre' => '26'),
			array('id' => '753','nombre' => 'Pensiones','idPadre' => '26'),
			array('id' => '754','nombre' => 'Posadas','idPadre' => '26'),
			array('id' => '755','nombre' => 'Automatización','idPadre' => '27'),
			array('id' => '756','nombre' => 'Aeronáutica','idPadre' => '27'),
			array('id' => '757','nombre' => 'Biométrica','idPadre' => '27'),
			array('id' => '758','nombre' => 'Diseño Industrial','idPadre' => '27'),
			array('id' => '759','nombre' => 'Energías Renovables','idPadre' => '27'),
			array('id' => '760','nombre' => 'Ingeniería Acústica','idPadre' => '27'),
			array('id' => '761','nombre' => 'Ingeniería Civil','idPadre' => '27'),
			array('id' => '762','nombre' => 'Ingeniería Eléctrica','idPadre' => '27'),
			array('id' => '763','nombre' => 'Ingeniería Edificación','idPadre' => '27'),
			array('id' => '764','nombre' => 'Ingeniería Energética','idPadre' => '27'),
			array('id' => '765','nombre' => 'Ingeniería Forestal','idPadre' => '27'),
			array('id' => '766','nombre' => 'Ingeniería Química','idPadre' => '27'),
			array('id' => '767','nombre' => 'Ingeniería Industrial','idPadre' => '27'),
			array('id' => '768','nombre' => 'Ingeniería Naval','idPadre' => '27'),
			array('id' => '769','nombre' => 'Ingeniería Minas','idPadre' => '27'),
			array('id' => '770','nombre' => 'Telecomunicaciones','idPadre' => '27'),
			array('id' => '771','nombre' => 'Proyectos Ingeniería','idPadre' => '27'),
			array('id' => '772','nombre' => 'Peritajes Judiciales','idPadre' => '27'),
			array('id' => '773','nombre' => 'Actividades Infantiles','idPadre' => '28'),
			array('id' => '774','nombre' => 'Bebés','idPadre' => '28'),
			array('id' => '775','nombre' => 'Decoración Infantil','idPadre' => '28'),
			array('id' => '776','nombre' => 'Fiestas Infantiles','idPadre' => '28'),
			array('id' => '777','nombre' => 'Guarderías','idPadre' => '28'),
			array('id' => '778','nombre' => 'Jardín de Infancia','idPadre' => '28'),
			array('id' => '779','nombre' => 'Jugueterías','idPadre' => '28'),
			array('id' => '780','nombre' => 'Moda Infantil','idPadre' => '28'),
			array('id' => '781','nombre' => 'Muebles Infantiles','idPadre' => '28'),
			array('id' => '782','nombre' => 'Psicología Infantil','idPadre' => '28'),
			array('id' => '783','nombre' => 'Ropa Infantil','idPadre' => '28'),
			array('id' => '784','nombre' => 'Consumibles Informáticos','idPadre' => '29'),
			array('id' => '785','nombre' => 'Franquicias Informática','idPadre' => '29'),
			array('id' => '786','nombre' => 'Ingeniería Informática','idPadre' => '29'),
			array('id' => '787','nombre' => 'Ingeniería Software','idPadre' => '29'),
			array('id' => '788','nombre' => 'Informática Empresas','idPadre' => '29'),
			array('id' => '789','nombre' => 'Mayorista Informática','idPadre' => '29'),
			array('id' => '790','nombre' => 'Mantenimiento Informático','idPadre' => '29'),
			array('id' => '791','nombre' => 'Ofimática','idPadre' => '29'),
			array('id' => '792','nombre' => 'Segunda Mano Informática','idPadre' => '29'),
			array('id' => '793','nombre' => 'Seguridad Informática','idPadre' => '29'),
			array('id' => '794','nombre' => 'Tienda Informática','idPadre' => '29'),
			array('id' => '795','nombre' => 'Programación Informática','idPadre' => '29'),
			array('id' => '796','nombre' => 'Administrador de Comunidades','idPadre' => '31'),
			array('id' => '797','nombre' => 'Áticos','idPadre' => '31'),
			array('id' => '798','nombre' => 'Alquiler de Despachos','idPadre' => '31'),
			array('id' => '799','nombre' => 'Alquiler de Oficinas','idPadre' => '31'),
			array('id' => '800','nombre' => 'Alquiler de Pisos','idPadre' => '31'),
			array('id' => '801','nombre' => 'Compra Venta de Inmuebles','idPadre' => '31'),
			array('id' => '802','nombre' => 'Garajes','idPadre' => '31'),
			array('id' => '803','nombre' => 'Locales','idPadre' => '31'),
			array('id' => '804','nombre' => 'Mudanzas','idPadre' => '31'),
			array('id' => '805','nombre' => 'Pisos de Segunda Mano','idPadre' => '31'),
			array('id' => '806','nombre' => 'Promotoras','idPadre' => '31'),
			array('id' => '807','nombre' => 'Parcelas','idPadre' => '31'),
			array('id' => '808','nombre' => 'Terrenos','idPadre' => '31'),
			array('id' => '809','nombre' => 'Abonos','idPadre' => '32'),
			array('id' => '810','nombre' => 'Adornos Jardines','idPadre' => '32'),
			array('id' => '811','nombre' => 'Ajardinamientos','idPadre' => '32'),
			array('id' => '812','nombre' => 'Arreglos Florales','idPadre' => '32'),
			array('id' => '813','nombre' => 'Cesped','idPadre' => '32'),
			array('id' => '814','nombre' => 'Diseño Jardines','idPadre' => '32'),
			array('id' => '815','nombre' => 'Fertilizantes','idPadre' => '32'),
			array('id' => '816','nombre' => 'Floristería','idPadre' => '32'),
			array('id' => '817','nombre' => 'Herramientas Jardinería','idPadre' => '32'),
			array('id' => '818','nombre' => 'Invernaderos','idPadre' => '32'),
			array('id' => '819','nombre' => 'Jardineros','idPadre' => '32'),
			array('id' => '820','nombre' => 'Mantenimiento Parques','idPadre' => '32'),
			array('id' => '821','nombre' => 'Paisajismo','idPadre' => '32'),
			array('id' => '822','nombre' => 'Pérgolas','idPadre' => '32'),
			array('id' => '823','nombre' => 'Plantas','idPadre' => '32'),
			array('id' => '824','nombre' => 'Podas','idPadre' => '32'),
			array('id' => '825','nombre' => 'Productos Jardinería','idPadre' => '32'),
			array('id' => '826','nombre' => 'Serrerías','idPadre' => '32'),
			array('id' => '827','nombre' => 'Sistemas Riego','idPadre' => '32'),
			array('id' => '828','nombre' => 'Desinfección','idPadre' => '33'),
			array('id' => '829','nombre' => 'Desinsectación','idPadre' => '33'),
			array('id' => '830','nombre' => 'Empresa Limpieza','idPadre' => '33'),
			array('id' => '831','nombre' => 'Lavanderías','idPadre' => '33'),
			array('id' => '832','nombre' => 'Limpieza Coches','idPadre' => '33'),
			array('id' => '833','nombre' => 'Limpieza Comunidades','idPadre' => '33'),
			array('id' => '834','nombre' => 'Limpieza Cristales','idPadre' => '33'),
			array('id' => '835','nombre' => 'Limpieza Doméstica','idPadre' => '33'),
			array('id' => '836','nombre' => 'Limpieza Ecológica','idPadre' => '33'),
			array('id' => '837','nombre' => 'Limpieza Fachadas','idPadre' => '33'),
			array('id' => '838','nombre' => 'Limpieza Industrial','idPadre' => '33'),
			array('id' => '839','nombre' => 'Limpieza Mantenimiento','idPadre' => '33'),
			array('id' => '840','nombre' => 'Limpieza Oficinas','idPadre' => '33'),
			array('id' => '841','nombre' => 'Limpieza Piscinas','idPadre' => '33'),
			array('id' => '842','nombre' => 'Limpieza Parques','idPadre' => '33'),
			array('id' => '843','nombre' => 'Productos Limpieza','idPadre' => '33'),
			array('id' => '844','nombre' => 'Saneamientos','idPadre' => '33'),
			array('id' => '845','nombre' => 'Túnel Lavado','idPadre' => '33'),
			array('id' => '846','nombre' => 'Tintorerías','idPadre' => '33'),
			array('id' => '847','nombre' => 'Asistencia Técnica','idPadre' => '34'),
			array('id' => '848','nombre' => 'Aire Acondicionado','idPadre' => '34'),
			array('id' => '849','nombre' => 'Mantenimiento de Edificios','idPadre' => '34'),
			array('id' => '850','nombre' => 'Mantenimiento de Extintores','idPadre' => '34'),
			array('id' => '851','nombre' => 'Mantenimiento de Fincas','idPadre' => '34'),
			array('id' => '852','nombre' => 'Mantenimiento Integral','idPadre' => '34'),
			array('id' => '853','nombre' => 'Mantenimiento de Piscinas','idPadre' => '34'),
			array('id' => '854','nombre' => 'Mantenimiento Telefónico','idPadre' => '34'),
			array('id' => '855','nombre' => 'Reparación a Domicilio','idPadre' => '34'),
			array('id' => '856','nombre' => 'Talleres Mecánicos','idPadre' => '34'),
			array('id' => '857','nombre' => 'Clínicas Privadas','idPadre' => '35'),
			array('id' => '858','nombre' => 'Dentistas','idPadre' => '35'),
			array('id' => '859','nombre' => 'Farmacias','idPadre' => '35'),
			array('id' => '860','nombre' => 'Médicos','idPadre' => '35'),
			array('id' => '861','nombre' => 'Mutuas','idPadre' => '35'),
			array('id' => '862','nombre' => 'Psicólogos','idPadre' => '35'),
			array('id' => '863','nombre' => 'Psiquiatras','idPadre' => '35'),
			array('id' => '864','nombre' => 'Reconocimientos Médicos','idPadre' => '35'),
			array('id' => '865','nombre' => 'Tercera Edad','idPadre' => '35'),
			array('id' => '867','nombre' => 'Alta Costura','idPadre' => '36'),
			array('id' => '868','nombre' => 'Complementos','idPadre' => '36'),
			array('id' => '869','nombre' => 'Boutique Ropa','idPadre' => '36'),
			array('id' => '870','nombre' => 'Bolsos','idPadre' => '36'),
			array('id' => '871','nombre' => 'Calzado','idPadre' => '36'),
			array('id' => '872','nombre' => 'Confección','idPadre' => '36'),
			array('id' => '873','nombre' => 'Gafas','idPadre' => '36'),
			array('id' => '874','nombre' => 'Moda Caballero','idPadre' => '36'),
			array('id' => '875','nombre' => 'Moda Señora','idPadre' => '36'),
			array('id' => '876','nombre' => 'Moda Juvenil','idPadre' => '36'),
			array('id' => '877','nombre' => 'Moda Infantil','idPadre' => '36'),
			array('id' => '878','nombre' => 'Modistas','idPadre' => '36'),
			array('id' => '879','nombre' => 'Ropa Segunda Mano','idPadre' => '36'),
			array('id' => '880','nombre' => 'Ropa Laboral','idPadre' => '36'),
			array('id' => '881','nombre' => 'Ropa Hogar','idPadre' => '36'),
			array('id' => '882','nombre' => 'Sastrerías','idPadre' => '36'),
			array('id' => '883','nombre' => 'Tienda Ropa','idPadre' => '36'),
			array('id' => '884','nombre' => 'Zapaterías','idPadre' => '36'),
			array('id' => '885','nombre' => 'Bares','idPadre' => '37'),
			array('id' => '886','nombre' => 'Barranquismo','idPadre' => '37'),
			array('id' => '887','nombre' => 'Cafeterías','idPadre' => '37'),
			array('id' => '888','nombre' => 'Casinos','idPadre' => '37'),
			array('id' => '889','nombre' => 'Escalada','idPadre' => '37'),
			array('id' => '890','nombre' => 'Galerías de Arte','idPadre' => '37'),
			array('id' => '891','nombre' => 'Loterías y Apuestas','idPadre' => '37'),
			array('id' => '892','nombre' => 'Museos','idPadre' => '37'),
			array('id' => '893','nombre' => 'Ocio Activo','idPadre' => '37'),
			array('id' => '894','nombre' => 'Picaderos','idPadre' => '37'),
			array('id' => '895','nombre' => 'Teatros','idPadre' => '37'),
			array('id' => '896','nombre' => 'Videojuegos','idPadre' => '37'),
			array('id' => '897','nombre' => 'Videoclubes','idPadre' => '37'),
			array('id' => '898','nombre' => 'Venta de Piscinas','idPadre' => '37'),
			array('id' => '899','nombre' => 'Instrumentos Musicales','idPadre' => '37'),
			array('id' => '901','nombre' => 'Bingos','idPadre' => '37'),
			array('id' => '902','nombre' => 'Agencias de Publicidad','idPadre' => '38'),
			array('id' => '903','nombre' => 'Audiovisuales','idPadre' => '38'),
			array('id' => '904','nombre' => 'Diseño Gráfico','idPadre' => '38'),
			array('id' => '905','nombre' => 'Fotógrafos Publicitarios','idPadre' => '38'),
			array('id' => '906','nombre' => 'Imprenta','idPadre' => '38'),
			array('id' => '907','nombre' => 'Impresión Digital','idPadre' => '38'),
			array('id' => '908','nombre' => 'Márketing','idPadre' => '38'),
			array('id' => '909','nombre' => 'Productoras','idPadre' => '38'),
			array('id' => '910','nombre' => 'Publicidad Exterior','idPadre' => '38'),
			array('id' => '911','nombre' => 'Promociones','idPadre' => '38'),
			array('id' => '912','nombre' => 'Regalos Publicitarios','idPadre' => '38'),
			array('id' => '913','nombre' => 'Soportes Publicitarios','idPadre' => '38'),
			array('id' => '914','nombre' => 'Alta Cocina','idPadre' => '502'),
			array('id' => '915','nombre' => 'Bodegas','idPadre' => '502'),
			array('id' => '916','nombre' => 'Cocina a la Brasa','idPadre' => '502'),
			array('id' => '917','nombre' => 'Cocina Asiática','idPadre' => '502'),
			array('id' => '918','nombre' => 'Cocina Casera','idPadre' => '502'),
			array('id' => '919','nombre' => 'Cocina Creativa','idPadre' => '502'),
			array('id' => '920','nombre' => 'Cocina Oriental','idPadre' => '502'),
			array('id' => '921','nombre' => 'Cocina Vegetariana','idPadre' => '502'),
			array('id' => '922','nombre' => 'Marisquería','idPadre' => '502'),
			array('id' => '923','nombre' => 'Menú del Día','idPadre' => '502'),
			array('id' => '924','nombre' => 'Restaurante Asturiano','idPadre' => '502'),
			array('id' => '925','nombre' => 'Restaurante Argentino','idPadre' => '502'),
			array('id' => '926','nombre' => 'Restaurante Chino','idPadre' => '502'),
			array('id' => '927','nombre' => 'Restaurante Cubano','idPadre' => '502'),
			array('id' => '928','nombre' => 'Restaurante Italiano','idPadre' => '502'),
			array('id' => '929','nombre' => 'Restaurantes Temáticos','idPadre' => '502'),
			array('id' => '930','nombre' => 'Tabernas','idPadre' => '502'),
			array('id' => '931','nombre' => 'Tapas','idPadre' => '502'),
			array('id' => '932','nombre' => 'Vinaterías','idPadre' => '502'),
			array('id' => '933','nombre' => 'Alarmas','idPadre' => '503'),
			array('id' => '934','nombre' => 'Cerrajeros','idPadre' => '503'),
			array('id' => '935','nombre' => 'Cajas Fuertes','idPadre' => '503'),
			array('id' => '936','nombre' => 'Empresa Vigilancia','idPadre' => '503'),
			array('id' => '937','nombre' => 'Empresa Seguridad','idPadre' => '503'),
			array('id' => '938','nombre' => 'Extintores','idPadre' => '503'),
			array('id' => '939','nombre' => 'Puertas Blindadas','idPadre' => '503'),
			array('id' => '940','nombre' => 'Videovigilancia','idPadre' => '503'),
			array('id' => '941','nombre' => 'Vigilante jurado','idPadre' => '503'),
			array('id' => '942','nombre' => 'Corredurías seguros','idPadre' => '504'),
			array('id' => '943','nombre' => 'Peritos','idPadre' => '504'),
			array('id' => '944','nombre' => 'Tasadores','idPadre' => '504'),
			array('id' => '945','nombre' => 'Seguros Coche','idPadre' => '504'),
			array('id' => '946','nombre' => 'Seguros Hogar','idPadre' => '504'),
			array('id' => '947','nombre' => 'Seguros Médicos','idPadre' => '504'),
			array('id' => '948','nombre' => 'Seguros vida','idPadre' => '504'),
			array('id' => '949','nombre' => 'Seguridad Alimentaria','idPadre' => '504'),
			array('id' => '950','nombre' => 'Seguridad Privada','idPadre' => '504'),
			array('id' => '951','nombre' => 'Seguridad Laboral','idPadre' => '504'),
			array('id' => '952','nombre' => 'Seguros Inmobiliarios','idPadre' => '504'),
			array('id' => '953','nombre' => 'Agencias de Transporte','idPadre' => '505'),
			array('id' => '954','nombre' => 'Almacén de Mercancías','idPadre' => '505'),
			array('id' => '955','nombre' => 'Alquiler de Autocares','idPadre' => '505'),
			array('id' => '956','nombre' => 'Autobuses','idPadre' => '505'),
			array('id' => '958','nombre' => 'Camiones','idPadre' => '505'),
			array('id' => '959','nombre' => 'Compañías Aéreas','idPadre' => '505'),
			array('id' => '960','nombre' => 'Empresas de Mudanzas','idPadre' => '505'),
			array('id' => '961','nombre' => 'Ferrocarriles','idPadre' => '505'),
			array('id' => '962','nombre' => 'Furgonetas','idPadre' => '505'),
			array('id' => '963','nombre' => 'Limusinas','idPadre' => '505'),
			array('id' => '964','nombre' => 'Líneas Marítimas','idPadre' => '505'),
			array('id' => '965','nombre' => 'Logística','idPadre' => '505'),
			array('id' => '966','nombre' => 'Mensajerías','idPadre' => '505'),
			array('id' => '967','nombre' => 'Paquetería','idPadre' => '505'),
			array('id' => '968','nombre' => 'Repartos','idPadre' => '505'),
			array('id' => '969','nombre' => 'Taxistas','idPadre' => '505'),
			array('id' => '970','nombre' => 'Transporte Escolar','idPadre' => '505'),
			array('id' => '971','nombre' => 'Transporte Carretera','idPadre' => '505'),
			array('id' => '972','nombre' => 'Accesorios para Vehículos','idPadre' => '506'),
			array('id' => '973','nombre' => 'Gasolineras','idPadre' => '506'),
			array('id' => '974','nombre' => 'Tasación de Vehículos','idPadre' => '506'),
			array('id' => '975','nombre' => 'Taller Mecánico','idPadre' => '506'),
			array('id' => '976','nombre' => 'Túnel de Lavado','idPadre' => '506'),
			array('id' => '977','nombre' => 'Vehículos Industriales','idPadre' => '506'),
			array('id' => '978','nombre' => 'Vehículos Comerciales','idPadre' => '506'),
			array('id' => '979','nombre' => 'Venta de Vehículos','idPadre' => '506'),
			array('id' => '980','nombre' => 'Agencia de Viajes','idPadre' => '507'),
			array('id' => '981','nombre' => 'Artículos de Viaje','idPadre' => '507'),
			array('id' => '982','nombre' => 'Excursiones','idPadre' => '507'),
			array('id' => '983','nombre' => 'Touroperadores','idPadre' => '507'),
			array('id' => '984','nombre' => 'Turismo Rural','idPadre' => '507'),
			array('id' => '985','nombre' => 'Viajes de Empresa','idPadre' => '507'),
			array('id' => '986','nombre' => 'Viajes de Novios','idPadre' => '507'),
			array('id' => '987','nombre' => 'Viajes Multiaventura','idPadre' => '507'),
			array('id' => '988','nombre' => 'Viajes a la carta','idPadre' => '507'),
			array('id' => '989','nombre' => 'Viajes para Solteros','idPadre' => '507')
		);
		foreach ($categorias as $categoria) {
			$entidad = new Categoria();
			$entidad->setId($categoria['id']);
			$entidad->setNombre($categoria['nombre']);
			$entidad->setIdPadre($manager->find('AppBundle:categoria', $categoria['idPadre']));
			$manager->persist($entidad);
		}
		$manager->flush();
	}
} 
