<?php
namespace AppBundle\DataFixtures\ORM;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use AppBundle\Entity\Ficha;
use AppBundle\Entity\Categoria;
class Fichas implements FixtureInterface
{
	public function load(ObjectManager $manager)
	{
		$fichas = array(
			array('id' => '2','titulo' => 'A.C.F. ABOGADOS SOCIEDAD DE ESTUDIOS LEGALES','categoria' => '9','calle' => 'Falsa 123','codigoPostal' => '47013','ciudad' => 'Valladolid','provincia' => 'Valladolid','comunidadAutonoma' => 'Castilla y LeÃ³n','pais' => 'EspaÃ±a','email' => 'a@b.c','web' => 'www.a.com','personaDeContacto' => NULL,'telefono' => '665544332','fax' => '345678909','hotline' => NULL,'decripcion' => 'desc','longitud' => '-1','latitud' => '1','pobacion' => 'Valladolid','decripcionLarga' => 'desc2','cif' => '45678A','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '3','titulo' => 'AB ABOGADOS','categoria' => '9','calle' => 'C/ Melquiades ï¿½lvarez nï¿½ 20 - 6ï¿½ B','codigoPostal' => 'fd033','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'borjabog@hotmail.com','web' => 'www.abogadosab.com','personaDeContacto' => NULL,'telefono' => '985217159','fax' => '0','hotline' => NULL,'decripcion' => 'AB ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'AB ABOGADOS','cif' => '32875127-P','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '4','titulo' => 'ABOGADO ÁLVARO RODRÍGUEZ MARTÍNEZ','categoria' => '9','calle' => 'Avda. Ordoño II, 30 - Entreplanta 25','codigoPostal' => '24001','ciudad' => 'LEÓN','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'juridicaley@yahoo.es','web' => 'www.juridicaley.es','personaDeContacto' => NULL,'telefono' => '669904110','fax' => '0','hotline' => NULL,'decripcion' => 'ABOGADO ÁLVARO RODRÍGUEZ MARTÍNEZ','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'ABOGADO ÁLVARO RODRÍGUEZ MARTÍNEZ','cif' => 'X-08761252-T','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '5','titulo' => 'ABOGADOS FERNANDEZ - PAREDES','categoria' => '9','calle' => 'CONDE TORENO, 1 - 2º DCHA','codigoPostal' => '33004','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'fparedes@fernandezparedes.com','web' => 'www.fernandezparedes.com.pyme','personaDeContacto' => NULL,'telefono' => '985241790','fax' => '985241660','hotline' => NULL,'decripcion' => 'ABOGADOS FERNANDEZ - PAREDES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ABOGADOS FERNANDEZ - PAREDES','cif' => 'J-33414376','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '6','titulo' => 'ABOGADOS JUNQUERA & ANTA','categoria' => '9','calle' => 'LOS MOROS, 38, 1º IZQUIERDA','codigoPostal' => '33206','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'mag1851@colegiados.icagijon.es','web' => 'www.junquerayantaabogados.com','personaDeContacto' => NULL,'telefono' => '985346353','fax' => '985346373','hotline' => NULL,'decripcion' => 'ABOGADOS JUNQUERA & ANTA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ABOGADOS JUNQUERA & ANTA','cif' => 'J-33967126','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '7','titulo' => 'ADMINISTRACION DE FINCAS JOVELLANOS','categoria' => '9','calle' => 'C/ ASTURIAS,4-3ºDCHA.','codigoPostal' => '33206','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'admjov@administracionesjovellanos.com','web' => 'www.administracionesjovellanos.com.pyme','personaDeContacto' => NULL,'telefono' => '985356092','fax' => '985352324','hotline' => NULL,'decripcion' => 'ADMINISTRACION DE FINCAS JOVELLANOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ADMINISTRACION DE FINCAS JOVELLANOS','cif' => 'E-33814609','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '8','titulo' => 'ADOLFO VENTA ABOGADO','categoria' => '9','calle' => 'C/ BEGOÑA,  60 - 1º','codigoPostal' => '33201','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'adolfoventaabogado@telecable.es','web' => 'www.adolfoventaabogado.es','personaDeContacto' => NULL,'telefono' => '985345393','fax' => '0','hotline' => NULL,'decripcion' => 'ADOLFO VENTA ABOGADO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ADOLFO VENTA ABOGADO','cif' => '10758321-W','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '9','titulo' => 'ALIANZA ABOGADOS','categoria' => '9','calle' => 'C/ Uria nº 48 - 3º C','codigoPostal' => '33003','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'alianzaabogados@terra.es','web' => 'www.alianzaabogados.net','personaDeContacto' => NULL,'telefono' => '985205444','fax' => '985227027','hotline' => NULL,'decripcion' => 'ALIANZA ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ALIANZA ABOGADOS','cif' => 'G-33557307','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '10','titulo' => 'ALVAREZ & CECCHINI ABOGADOS CB','categoria' => '9','calle' => 'GIL DE JAZ, 4 - 6ºC','codigoPostal' => '33004','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'alvarezycecchini@letrados.com','web' => 'www.alvarezycecchiniabogados.com','personaDeContacto' => NULL,'telefono' => '985276069','fax' => '984151490','hotline' => NULL,'decripcion' => 'ALVAREZ & CECCHINI ABOGADOS CB','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ALVAREZ & CECCHINI ABOGADOS CB','cif' => 'E-74124322','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '11','titulo' => 'ALVAREZ Y GARCIA-BARREDO ABOGADOS','categoria' => '9','calle' => 'CALLE ASTURIAS,34, ESCALERA DCHA, 1ºC','codigoPostal' => '33004','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'despacho@locusiuris.com','web' => 'www.locusiuris.com.pyme','personaDeContacto' => NULL,'telefono' => '985207704','fax' => '984151986','hotline' => NULL,'decripcion' => 'ALVAREZ Y GARCIA-BARREDO ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ALVAREZ Y GARCIA-BARREDO ABOGADOS','cif' => 'B-74193657','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '13','titulo' => 'ANA INMACULADA GONZÁLEZ SOBREDO','categoria' => '9','calle' => 'CUESTA DE LA PALLOZA, 5. PISO  20. DESPACHO  3','codigoPostal' => '15006','ciudad' => 'A CORUÑA','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'ana@gonzalezsobredo.es','web' => 'www.gonzalezsobredo.es','personaDeContacto' => NULL,'telefono' => '881101666','fax' => '881101654','hotline' => NULL,'decripcion' => 'ANA INMACULADA GONZÁLEZ SOBREDO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'ANA INMACULADA GONZÁLEZ SOBREDO','cif' => '10083481-M','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '14','titulo' => 'ANA ISABEL RUIZ GUTIERREZ','categoria' => '9','calle' => 'MARQUES DE SAN ESTEBAN, 39 -  6º CENTRO','codigoPostal' => '33206','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'anairuiz@terra.es','web' => 'www.admonfincasgijon.com','personaDeContacto' => NULL,'telefono' => '985350822','fax' => '984292033','hotline' => NULL,'decripcion' => 'ANA ISABEL RUIZ GUTIERREZ','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ANA ISABEL RUIZ GUTIERREZ','cif' => '10835412-C','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '15','titulo' => 'ANTONIO DE LORENZO Y ASOCIADOS','categoria' => '9','calle' => 'C/ Celestino Junquera nº 2, 3º, Of 36','codigoPostal' => '33201','ciudad' => 'GIJÓN','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'abogado@lorenzoasesor.com','web' => 'www.lorenzoasesor.com','personaDeContacto' => NULL,'telefono' => '984050959','fax' => '985170177','hotline' => NULL,'decripcion' => 'ANTONIO DE LORENZO Y ASOCIADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ANTONIO DE LORENZO Y ASOCIADOS','cif' => '10834336-W','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '16','titulo' => 'BERAMENDI Y GONZALEZ ABOGADOS SLP','categoria' => '9','calle' => 'C/  Tomás Zarracina, 1 - 2º A','codigoPostal' => '33206','ciudad' => 'Gijón','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'jm@beramendiygonzalez.com','web' => 'www.beramendiygonzalez.com','personaDeContacto' => NULL,'telefono' => '985170250','fax' => '985172085','hotline' => NULL,'decripcion' => 'BERAMENDI Y GONZALEZ ABOGADOS SLP','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'BERAMENDI Y GONZALEZ ABOGADOS SLP','cif' => 'B-33819897','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '18','titulo' => 'BUFETE DE ABOGADOS MANUEL FERNÁNDEZ ÁLVAREZ','categoria' => '9','calle' => 'PLAZA DE AMERICA, 3 - 1º','codigoPostal' => '33005','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'cristina@bufetemanuelfernandez.com','web' => 'www.bufetemanuelfernandez.es','personaDeContacto' => NULL,'telefono' => '985242113','fax' => '985272010','hotline' => NULL,'decripcion' => 'BUFETE DE ABOGADOS MANUEL FERNÁNDEZ ÁLVAREZ','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'BUFETE DE ABOGADOS MANUEL FERNÁNDEZ ÁLVAREZ','cif' => '10504152-Y','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '19','titulo' => 'BUFETE DÍEZ & VECINO','categoria' => '9','calle' => 'AVDA. ORDOÑO II,  33 - 2ºA','codigoPostal' => '24001','ciudad' => 'LEÓN','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'idiezabogado@hotmail.com','web' => 'www.bufetediezyvecinoabogados.com','personaDeContacto' => NULL,'telefono' => '987093336','fax' => '0','hotline' => NULL,'decripcion' => 'BUFETE DÍEZ & VECINO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'BUFETE DÍEZ & VECINO','cif' => '09753457-P','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '20','titulo' => 'BUFETE INCLÁN MÉNDEZ','categoria' => '9','calle' => 'AVDA DE LA COSTA 87, 3º OF 8','codigoPostal' => '33205','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'germanramon@telecable.es','web' => 'www.bufeteinclanmendez.es','personaDeContacto' => NULL,'telefono' => '985350290','fax' => '0','hotline' => NULL,'decripcion' => 'BUFETE INCLÁN MÉNDEZ','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'BUFETE INCLÁN MÉNDEZ','cif' => '10842163-D','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '21','titulo' => 'BUFETE JURIDICO HORIZONTE','categoria' => '9','calle' => 'MARQUES DE SAN ESTEBAN, 46, 3º PUERTA 4','codigoPostal' => '33206','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'bufetejuridicohorizonte@gmail.com','web' => 'www.bufetejuridicohorizonte.es','personaDeContacto' => NULL,'telefono' => '985171719','fax' => '985175162','hotline' => NULL,'decripcion' => 'BUFETE JURIDICO HORIZONTE','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'BUFETE JURIDICO HORIZONTE','cif' => 'B-33963745','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '22','titulo' => 'CELSO GARCIA GARCIA','categoria' => '9','calle' => 'RIO SAN PEDRO, 4 1º DCHA','codigoPostal' => '33001','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'gdabogados@hotmail.com','web' => 'www.celsogarcia.es','personaDeContacto' => NULL,'telefono' => '985295070','fax' => '0','hotline' => NULL,'decripcion' => 'CELSO GARCIA GARCIA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'CELSO GARCIA GARCIA','cif' => '50844766-T','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '23','titulo' => 'CENTRO DE SINIESTROS RECOBROS E IMPAGOS (C. S. R. I.)','categoria' => '9','calle' => 'Plaza Fuente Dorada, 17, 3º - B','codigoPostal' => '47002','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'jgr@csri.e.telefonica.net','web' => 'www.csri.es','personaDeContacto' => NULL,'telefono' => '983218383','fax' => '983211077','hotline' => NULL,'decripcion' => 'CENTRO DE SINIESTROS RECOBROS E IMPAGOS (C. S. R. I.)','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'CENTRO DE SINIESTROS RECOBROS E IMPAGOS (C. S. R. I.)','cif' => 'B-47446984','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '24','titulo' => 'CONTRERAS, SOTO Y SANCHEZ HERRANZ, C.B.','categoria' => '9','calle' => 'C/ GRAN VIA, 97 2ºDCHA.','codigoPostal' => '37001','ciudad' => 'SALAMANCA','provincia' => 'Salamanca','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'juanluissanchez@asesoresjuridicos.onored.com','web' => 'www.contrerassotoysanchezherranz.es','personaDeContacto' => NULL,'telefono' => '923214049','fax' => '923211005','hotline' => NULL,'decripcion' => 'CONTRERAS, SOTO Y SANCHEZ HERRANZ, C.B.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'salamanca','decripcionLarga' => 'CONTRERAS, SOTO Y SANCHEZ HERRANZ, C.B.','cif' => 'E-37451184','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '25','titulo' => 'ALBERTO FERNANDEZ ASUETA','categoria' => '9','calle' => 'CONDE DE GUADALHORCE, 2 - 1ºC','codigoPostal' => '33206','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => '','pais' => 'España','email' => 'asueta_abogados@hotmail.com','web' => 'http://www.asueta-abogados.com','personaDeContacto' => NULL,'telefono' => '985171708','fax' => '985171708','hotline' => NULL,'decripcion' => '<p>ALBERTO FERNANDEZ ASUETA</p>','longitud' => '','latitud' => '','pobacion' => 'asturias','decripcionLarga' => '<p>ALBERTO FERNANDEZ ASUETA</p>','cif' => '10854677-B','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '26','titulo' => 'FERNANDEZ RODRIGUEZ DE CASTRO, M.J.','categoria' => '9','calle' => 'C/ Dindurra nº 6 - 2º C','codigoPostal' => '33201','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'valdes_abogadas@hotmail.com','web' => 'www.valdesabogadas.com','personaDeContacto' => NULL,'telefono' => '985092898','fax' => '985092898','hotline' => NULL,'decripcion' => 'FERNANDEZ RODRIGUEZ DE CASTRO, M.J.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'FERNANDEZ RODRIGUEZ DE CASTRO, M.J.','cif' => '71862190-R','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '27','titulo' => 'FERNÁNDEZ Y LUACES ABOGADOS','categoria' => '9','calle' => 'ENRIQUE DEQUIDT HEVIA,  14 -  1º IZDA.','codigoPostal' => '15005','ciudad' => 'A CORUÑA','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'mafernandez@fernandezyluaces.es','web' => 'www.fernandezyluaces.com','personaDeContacto' => NULL,'telefono' => '981258887','fax' => '881922528','hotline' => NULL,'decripcion' => 'FERNÁNDEZ Y LUACES ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'FERNÁNDEZ Y LUACES ABOGADOS','cif' => 'J-15768054','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '29','titulo' => 'GABINETE ESGUEVA ABOGADOS','categoria' => '9','calle' => 'ESGUEVA 4- 5ºC','codigoPostal' => '47003','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'fparaiso@iacaba.org','web' => 'www.gabinetesgueva.com','personaDeContacto' => NULL,'telefono' => '928207154','fax' => '0','hotline' => NULL,'decripcion' => 'GABINETE ESGUEVA ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'GABINETE ESGUEVA ABOGADOS','cif' => '09281814-A','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '30','titulo' => 'GONZALO LOPEZ ABOGADOS','categoria' => '9','calle' => 'C/ Marqués de Teverga, 8,7ºA.','codigoPostal' => '33005','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'info@gonzalolopezabogados.es','web' => 'www.gonzalolopezabogados.es','personaDeContacto' => NULL,'telefono' => '985274913','fax' => '0','hotline' => NULL,'decripcion' => 'GONZALO LOPEZ ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'GONZALO LOPEZ ABOGADOS','cif' => '09391521-T','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '31','titulo' => 'HERNÁNDEZ ABOGADOS','categoria' => '9','calle' => 'MELQUIADES ALVAREZ,  12-1ºB','codigoPostal' => '33003','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'fjhernandez@hernandez-abogados.com','web' => 'www.hernandez-abogados.com.pyme','personaDeContacto' => NULL,'telefono' => '985229385','fax' => '985202861','hotline' => NULL,'decripcion' => 'HERNÁNDEZ ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'HERNÁNDEZ ABOGADOS','cif' => '09404535-L','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '33','titulo' => 'INSITU','categoria' => '9','calle' => 'RUA NUEVA, 18 - 3 I','codigoPostal' => '15003','ciudad' => 'A CORUÑA','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'info@insitu-a.com','web' => 'www.insitu-a.es','personaDeContacto' => NULL,'telefono' => '881252160','fax' => '0','hotline' => NULL,'decripcion' => 'INSITU','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'INSITU','cif' => '32700691-G','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '34','titulo' => 'JAVIER CALZADILLA BEUNZA','categoria' => '9','calle' => 'C/ Santa Susana nº 29 - 3º D','codigoPostal' => '33007','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'calzadilla@arquired.es','web' => 'www.calzadillaabogados.com','personaDeContacto' => NULL,'telefono' => '985235999','fax' => '0','hotline' => NULL,'decripcion' => 'JAVIER CALZADILLA BEUNZA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'JAVIER CALZADILLA BEUNZA','cif' => '09385919-X','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '35','titulo' => 'JAVIER SANTOS Y ASOCIADOS','categoria' => '9','calle' => 'LA REJA, 2-10  1º D','codigoPostal' => '37001','ciudad' => 'SALAMANCA','provincia' => 'Salamanca','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'eva@tgcgrupo.es','web' => 'www.tgcgrupo.es','personaDeContacto' => NULL,'telefono' => '923281120','fax' => '0','hotline' => NULL,'decripcion' => 'JAVIER SANTOS Y ASOCIADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'salamanca','decripcionLarga' => 'JAVIER SANTOS Y ASOCIADOS','cif' => 'B-37410909','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '36','titulo' => 'JESUSA.SANCHEZ VICTORMANUELSANCHEZ MARCOS','categoria' => '9','calle' => 'C/ SAN PABLO,28 3ºF','codigoPostal' => '37001','ciudad' => 'Salamanca','provincia' => 'Salamanca','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'victormsanchezm@wanadoo.es','web' => 'www.abogadossanchezmarcosypermuy.com','personaDeContacto' => NULL,'telefono' => '923210593','fax' => '923210593','hotline' => NULL,'decripcion' => 'JESUSA.SANCHEZ VICTORMANUELSANCHEZ MARCOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'salamanca','decripcionLarga' => 'JESUSA.SANCHEZ VICTORMANUELSANCHEZ MARCOS','cif' => '07873091-F','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '37','titulo' => 'JOSE LUIS NAVA MEANA','categoria' => '9','calle' => 'LANUZA, 11 3ª','codigoPostal' => '33211','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'jlnava@netcom.es','web' => 'www.joseluisnavaabogados.es','personaDeContacto' => NULL,'telefono' => '985148541','fax' => '0','hotline' => NULL,'decripcion' => 'JOSE LUIS NAVA MEANA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'JOSE LUIS NAVA MEANA','cif' => '10787958-S','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '38','titulo' => 'JUAN LUIS BERROS FOMBELLA','categoria' => '9','calle' => 'C/ Marquesa de Canillejas nº 35 - 1º H','codigoPostal' => '33510','ciudad' => 'POLA DE SIERO','provincia' => 'Asturias - Siero','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'jlberros@yahoo.es','web' => 'www.abogadosjuanluisberros.com','personaDeContacto' => NULL,'telefono' => '985725758','fax' => '985725758','hotline' => NULL,'decripcion' => 'JUAN LUIS BERROS FOMBELLA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'JUAN LUIS BERROS FOMBELLA','cif' => '52611579-E','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '39','titulo' => 'JURISNOR CONSULTORES','categoria' => '9','calle' => 'Avda. Galicia nº 17, 1º A','codigoPostal' => '33005','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'joaquincurto@jurisnor.com','web' => 'www.abogadosjurisnor.es','personaDeContacto' => NULL,'telefono' => '985237577','fax' => '0','hotline' => NULL,'decripcion' => 'JURISNOR CONSULTORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'JURISNOR CONSULTORES','cif' => 'B-74275876','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '40','titulo' => 'LEGISTA','categoria' => '9','calle' => 'C/ Los Moros nº 37','codigoPostal' => '33206','ciudad' => 'GIJON','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'danielmartinezabogados@gmail.com','web' => 'www.legistabogados.es','personaDeContacto' => NULL,'telefono' => '616919913','fax' => '0','hotline' => NULL,'decripcion' => 'LEGISTA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'LEGISTA','cif' => '10877680-Z','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '41','titulo' => 'LEON CUETO ABOGADOS','categoria' => '9','calle' => 'CURA SAMA 6 - 3ª IZ','codigoPostal' => '33202','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'saleon@wanadoo.es','web' => 'www.leoncuetoabogados.es','personaDeContacto' => NULL,'telefono' => '984195904','fax' => '0','hotline' => NULL,'decripcion' => 'LEON CUETO ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'LEON CUETO ABOGADOS','cif' => '10864220-D','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '42','titulo' => 'LEONARDO DIAZ - PEVIDA CANAL','categoria' => '9','calle' => 'Pl. AYUNTAMIENTO  17. 5 izq esc A','codigoPostal' => '33300','ciudad' => 'Villaviciosa','provincia' => 'Asturias - Villaviciosa','comunidadAutonoma' => NULL,'pais' => 'España','email' => '0','web' => 'www.leonardodiaz-pevida.com','personaDeContacto' => NULL,'telefono' => '985892179','fax' => '985892179','hotline' => NULL,'decripcion' => 'LEONARDO DIAZ - PEVIDA CANAL','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'LEONARDO DIAZ - PEVIDA CANAL','cif' => '10552715-Q','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '44','titulo' => 'LEXIFINCAS ABOGADOS Y ADMINISTRACIÓN DE FINCAS','categoria' => '9','calle' => 'C/ Torrecilla 14','codigoPostal' => '47003','ciudad' => 'Valladolid','provincia' => 'Valladolid','comunidadAutonoma' => '','pais' => 'España','email' => '0','web' => 'http://www.lexfincas.com','personaDeContacto' => NULL,'telefono' => '983253764','fax' => '983253764','hotline' => NULL,'decripcion' => '<p>LEXIFINCAS ABOGADOS Y ADMINISTRACIÓN DE FINCAS</p>','longitud' => '','latitud' => '','pobacion' => 'valladolid','decripcionLarga' => '<p>LEXIFINCAS ABOGADOS Y ADMINISTRACIÓN DE FINCAS</p>','cif' => '44903544-T','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '45','titulo' => 'MANUELA RUBIO MELENDEZ','categoria' => '9','calle' => 'Plaza de España nº 6 3º Oficina 34','codigoPostal' => '47001','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'manuelarub@gmail.com','web' => 'www.manuelaabogada.com','personaDeContacto' => NULL,'telefono' => '983206574','fax' => '983206574','hotline' => NULL,'decripcion' => 'MANUELA RUBIO MELENDEZ','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'MANUELA RUBIO MELENDEZ','cif' => '09753172-E','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '46','titulo' => 'MARIA DEL MAR FERNANDEZ IZQUIERDO','categoria' => '9','calle' => 'PLAZA CAMPINOS DE BEGOÑA,1-4ºC','codigoPostal' => '33201','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'mfiabogados@terra.es','web' => 'www.infoabogadas.com','personaDeContacto' => NULL,'telefono' => '985171389','fax' => '0','hotline' => NULL,'decripcion' => 'MARIA DEL MAR FERNANDEZ IZQUIERDO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'MARIA DEL MAR FERNANDEZ IZQUIERDO','cif' => '10857694-S','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '47','titulo' => 'MARÍA DEL ROSARIO MALLO - ABOGADA','categoria' => '9','calle' => 'CORRIDA, 48, 2º CENTRO','codigoPostal' => '33206','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'rosariomallo@telecable.es','web' => 'www.rosariomalloabogados.com','personaDeContacto' => NULL,'telefono' => '658953021','fax' => '0','hotline' => NULL,'decripcion' => 'MARÍA DEL ROSARIO MALLO - ABOGADA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'MARÍA DEL ROSARIO MALLO - ABOGADA','cif' => '11051158-A','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '48','titulo' => 'MARQUES FERNANDEZ,S.','categoria' => '9','calle' => 'TRAVESIA DEL CONVENTO,10-4ºC','codigoPostal' => '33202','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'cespinos@netcom.es','web' => 'www.marquesabogados.net','personaDeContacto' => NULL,'telefono' => '985171380','fax' => '985353110','hotline' => NULL,'decripcion' => 'MARQUES FERNANDEZ,S.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'MARQUES FERNANDEZ,S.','cif' => '10862639-S','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '49','titulo' => 'MIGUEL ANGEL QUINTANILLA CASADO','categoria' => '9','calle' => 'C/ SANTIAGO, 13 6º L','codigoPostal' => '47001','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'maquintanilla@terra.es','web' => 'www.abogadosvalladolid.es.pyme','personaDeContacto' => NULL,'telefono' => '661632569','fax' => '983117079','hotline' => NULL,'decripcion' => 'MIGUEL ANGEL QUINTANILLA CASADO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'MIGUEL ANGEL QUINTANILLA CASADO','cif' => '09313754-L','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '51','titulo' => 'MORENO ABOGADOS','categoria' => '9','calle' => 'C/ Telesforo Cuevas nº 2 - 1º D','codigoPostal' => '33005','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'administracion@morenodespacho.com','web' => 'www.morenodespacho.com.pyme','personaDeContacto' => NULL,'telefono' => '985231034','fax' => '0','hotline' => NULL,'decripcion' => 'MORENO ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'MORENO ABOGADOS','cif' => 'B-33567157','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '53','titulo' => 'NIETO ABOGADOS','categoria' => '9','calle' => 'PLAZA DE LUGO, 20 - 1º','codigoPostal' => '15004','ciudad' => 'A CORUÑA','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'nietoabogados@mundo-r.com','web' => 'www.nietoabogados.org','personaDeContacto' => NULL,'telefono' => '981226238','fax' => '981221713','hotline' => NULL,'decripcion' => 'NIETO ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'NIETO ABOGADOS','cif' => '32112777-Q','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '54','titulo' => 'PABLO CARVAJAL DE LA TORRE','categoria' => '9','calle' => 'C/ Rafael Alberti nº 1 - 5º C','codigoPostal' => '15009','ciudad' => 'A CORUÑA','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'pablocarvajaltorre@yahoo.com','web' => 'www.carvajaldelatorreabogados.com','personaDeContacto' => NULL,'telefono' => '981298535','fax' => '0','hotline' => NULL,'decripcion' => 'PABLO CARVAJAL DE LA TORRE','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'PABLO CARVAJAL DE LA TORRE','cif' => '32817720-D','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '55','titulo' => 'PEÑAS Y PORTILLA ARNAIZ ABOGADOS','categoria' => '9','calle' => 'AVENIDA CID, 110 2ªA','codigoPostal' => '9006','ciudad' => 'BURGOS','provincia' => 'Burgos','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'rober.portilla@icam.es','web' => 'www.ppabogados.es','personaDeContacto' => NULL,'telefono' => '947205638','fax' => '947200106','hotline' => NULL,'decripcion' => 'PEÑAS Y PORTILLA ARNAIZ ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'burgos','decripcionLarga' => 'PEÑAS Y PORTILLA ARNAIZ ABOGADOS','cif' => '13165047-P','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '56','titulo' => 'PORTAURBANA,S.L.','categoria' => '9','calle' => 'ATRIO DE SANTIAGO Nº 1 - 1º A','codigoPostal' => '47001','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'npedrol@augeabogados.es //vanessa@augeabogados.es','web' => 'www.portaurbana.es','personaDeContacto' => NULL,'telefono' => '983217221','fax' => '983217039','hotline' => NULL,'decripcion' => 'PORTAURBANA,S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'PORTAURBANA,S.L.','cif' => 'B-47522727','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '57','titulo' => 'RECALDE Y ASOCIADOS ABOGADOS','categoria' => '9','calle' => 'C/ URIA, 76 - 2º','codigoPostal' => '33003','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'federico@recaldeabogados.com','web' => 'www.recaldeabogados.com.pyme','personaDeContacto' => NULL,'telefono' => '985221278','fax' => '985203205','hotline' => NULL,'decripcion' => 'RECALDE Y ASOCIADOS ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'RECALDE Y ASOCIADOS ABOGADOS','cif' => '10594083-F','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '59','titulo' => 'SALINERO LAWYERS, S.C.P.','categoria' => '9','calle' => 'C/ GRAN VIA , 2 - 2ºA','codigoPostal' => '37001','ciudad' => 'SALAMANCA','provincia' => 'Salamanca','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'dagosa@salineroabogados.es','web' => 'www.salineroabogados.es','personaDeContacto' => NULL,'telefono' => '923603909','fax' => '923600150','hotline' => NULL,'decripcion' => 'SALINERO LAWYERS, S.C.P.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'salamanca','decripcionLarga' => 'SALINERO LAWYERS, S.C.P.','cif' => 'J-37492352','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '60','titulo' => 'SUAREZ Y TRELLES ABOGADOS','categoria' => '9','calle' => 'C/ ALVAREZ GARAYA, 1 - 3º IZDA.','codigoPostal' => '33206','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'st@suarezytrellesabogados.es','web' => 'www.suarezytrellesabogados.com','personaDeContacto' => NULL,'telefono' => '985350796','fax' => '0','hotline' => NULL,'decripcion' => 'SUAREZ Y TRELLES ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'SUAREZ Y TRELLES ABOGADOS','cif' => 'B-33954850','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '64','titulo' => 'VEREZ ASOCIADOS','categoria' => '9','calle' => 'PLZ.FCO.FDEZ DEL RIEGO Nº3 BAJO','codigoPostal' => '36203','ciudad' => 'VIGO - PONTEVEDRA','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'daniel@verezasociados.com','web' => 'www.verezasociados.com.pyme','personaDeContacto' => NULL,'telefono' => '886137434','fax' => '886139432','hotline' => NULL,'decripcion' => 'VEREZ ASOCIADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'VEREZ ASOCIADOS','cif' => 'B-36980936','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '65','titulo' => 'VERITAS ABOGADOS','categoria' => '9','calle' => 'LUIS BRAILE 8, 3º, LUGONES','codigoPostal' => '33420','ciudad' => 'SIERO','provincia' => 'Asturias - Siero','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'veritasabogados@hotmail.com','web' => 'www.veritasabogados.com','personaDeContacto' => NULL,'telefono' => '985267941','fax' => '985661606','hotline' => NULL,'decripcion' => 'VERITAS ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'VERITAS ABOGADOS','cif' => 'B-33599820','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '67','titulo' => 'VICTOR VELÁZQUEZ ABOGADO','categoria' => '9','calle' => 'RAMON Y CAJAL, 31 - 3ºIZDA','codigoPostal' => '24002','ciudad' => 'LEON','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'inaudita_parte_debitoris@hotmail.com','web' => 'www.victorvelazquezabogado.com','personaDeContacto' => NULL,'telefono' => '987224853','fax' => '0','hotline' => NULL,'decripcion' => 'VICTOR VELÁZQUEZ ABOGADO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'VICTOR VELÁZQUEZ ABOGADO','cif' => '09739848-S','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '2192','titulo' => 'JAVIER REGUERA GOMEZ (ABOGADOS R&T)/BUFETE COBO DEL ROSAL','categoria' => '9','calle' => 'C/ GARCIA PAREDES, 62- 1ºC','codigoPostal' => '28010','ciudad' => 'MADRID','provincia' => 'Madrid','comunidadAutonoma' => 'Comunidad de Madrid','pais' => 'España','email' => 'fcojavierreguera@hotmail.com','web' => 'www.abogadosryt.com','personaDeContacto' => NULL,'telefono' => '915943051','fax' => '915940396','hotline' => NULL,'decripcion' => 'Empresa de abogados en Madrid','longitud' => '0','latitud' => '0','pobacion' => 'madrid','decripcionLarga' => 'Empresa de abogados en Madrid','cif' => 'B-85515518','tipoFicha' => '3ficha_basica','perfilRedesSociales' => 'x—x'),
			array('id' => '2193','titulo' => 'ABOGADOS Y PUBLICIDAD, S.L.','categoria' => '9','calle' => 'C/ ORENSE,26 2ºD','codigoPostal' => '28020','ciudad' => 'MADRID','provincia' => 'Madrid','comunidadAutonoma' => 'Comunidad de Madrid','pais' => 'España','email' => 'serviciosjuridicos@abogadosypublicidad.com','web' => 'www.abogadosypublicidad.com.pyme','personaDeContacto' => NULL,'telefono' => '915983317','fax' => '915563114','hotline' => NULL,'decripcion' => 'Empresa de abogados en Madrid','longitud' => '-3.6945331','latitud' => '40.4379606','pobacion' => 'madrid','decripcionLarga' => 'Empresa de abogados en Madrid','cif' => 'B-84567890','tipoFicha' => '3ficha_basica','perfilRedesSociales' => 'x—x'),
			array('id' => '2194','titulo' => 'EDUARDO LUQUE ABOGADOS,S.L.','categoria' => '9','calle' => 'C/ INFANTA MERCEDES,96 1º','codigoPostal' => '28020','ciudad' => 'MADRID','provincia' => 'Madrid','comunidadAutonoma' => 'Comunidad de Madrid','pais' => 'España','email' => 'eluque@eluqueabogados.es','web' => 'www.eluqueabogados.es.pyme','personaDeContacto' => NULL,'telefono' => '914252990','fax' => '914252991','hotline' => NULL,'decripcion' => 'Empresa de abogados en Madrid','longitud' => '-3.6936683','latitud' => '40.4531323','pobacion' => 'madrid','decripcionLarga' => 'Empresa de abogados en Madrid','cif' => 'B-79555843','tipoFicha' => '3ficha_basica','perfilRedesSociales' => 'x—x'),
			array('id' => '2195','titulo' => 'VILLANUEVA Y BUENO','categoria' => '9','calle' => 'C/ CLARA DEL REY, 2 -  3º DERECHA','codigoPostal' => '28002','ciudad' => 'MADRID','provincia' => 'Madrid','comunidadAutonoma' => 'Comunidad de Madrid','pais' => 'España','email' => 'vmartinv@icam.es y 914011826@villanuevaybueno.com','web' => 'www.villanuevaybueno.com.pyme','personaDeContacto' => NULL,'telefono' => '914014264','fax' => '914011826','hotline' => NULL,'decripcion' => 'Empresa de abogados en Madrid','longitud' => '-3.6918404','latitud' => '40.4649994','pobacion' => 'madrid','decripcionLarga' => 'Empresa de abogados en Madrid','cif' => 'E-84355528','tipoFicha' => '3ficha_basica','perfilRedesSociales' => 'x—x'),
			array('id' => '253','titulo' => 'A.T.N. 2000, S.L.','categoria' => '10','calle' => 'C/ LA VEGA, 24 - 1º IZDA.','codigoPostal' => '33600','ciudad' => 'MIERES','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'atn2000sl@telecable.es','web' => 'www.atn2000sl.es','personaDeContacto' => NULL,'telefono' => '985450361','fax' => '985466423','hotline' => NULL,'decripcion' => 'A.T.N. 2000, S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'A.T.N. 2000, S.L.','cif' => 'B-33570045','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '256','titulo' => 'A3G AUDITORES','categoria' => '10','calle' => 'C/ VALENTIN MASIP,  7 - 1º','codigoPostal' => '33013','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'a3gauditores@a3gauditores.com','web' => 'www.a3gauditores.es','personaDeContacto' => NULL,'telefono' => '985255752','fax' => '0','hotline' => NULL,'decripcion' => 'A3G AUDITORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'A3G AUDITORES','cif' => 'B-74250119','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '257','titulo' => 'AD HOC Servicios Jurídicos','categoria' => '10','calle' => 'AVENIDA DE LA COSTA, 51, 1ºIZD','codigoPostal' => '33201','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'gabinetejuridico@telecable.es','web' => 'www.adhocjuridico.com','personaDeContacto' => NULL,'telefono' => '985170888','fax' => '985170999','hotline' => NULL,'decripcion' => 'AD HOC Servicios Jurídicos','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'AD HOC Servicios Jurídicos','cif' => 'B-33957879','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '258','titulo' => 'ADE, S.L.','categoria' => '10','calle' => 'AVDA. GRAN VIA DE SAN MARCOS 41- 1º C','codigoPostal' => '24002','ciudad' => 'LEON','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'ignacio20009@hotmail.com','web' => 'www.adeleon.es','personaDeContacto' => NULL,'telefono' => '987232234','fax' => '0','hotline' => NULL,'decripcion' => 'ADE, S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'ADE, S.L.','cif' => 'B-24562902','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '259','titulo' => 'ADINSA ASESORES','categoria' => '10','calle' => 'C/ FRAY CEFERINO, 49 - BAJO C','codigoPostal' => '33011','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'adinsalaurentino@telecable.es','web' => 'www.adinsaasesores.es','personaDeContacto' => NULL,'telefono' => '985205116','fax' => '985117181','hotline' => NULL,'decripcion' => 'ADINSA ASESORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ADINSA ASESORES','cif' => '09359430-V','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '260','titulo' => 'ADMIEMPRESA ASESORES','categoria' => '10','calle' => 'AVD. DE GALICIA, Nº 34','codigoPostal' => '33212','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'admiempresa@telefonica.net','web' => 'www.admiempresa.com.pyme','personaDeContacto' => NULL,'telefono' => '984391886','fax' => '984391886','hotline' => NULL,'decripcion' => 'ADMIEMPRESA ASESORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ADMIEMPRESA ASESORES','cif' => '09412165-J','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '261','titulo' => 'AFIGEM ASESORES','categoria' => '10','calle' => 'C/ BELMONTE DE MIRANDA,  6 - ENTLO. IZDA','codigoPostal' => '33206','ciudad' => 'GIJÓN','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'afigemasesores@terra.es','web' => 'www.afigemasesores.es','personaDeContacto' => NULL,'telefono' => '985359986','fax' => '0','hotline' => NULL,'decripcion' => 'AFIGEM ASESORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'AFIGEM ASESORES','cif' => 'B-33836495','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '262','titulo' => 'AFIM ASESORIA','categoria' => '10','calle' => 'C/ DONATO ARGÜELLES, 8 - 1º  OF. 5','codigoPostal' => '33206','ciudad' => 'GIJÓN','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'afim@telecable.es','web' => 'www.afimasesoria.es','personaDeContacto' => NULL,'telefono' => '984294841','fax' => '0','hotline' => NULL,'decripcion' => 'AFIM ASESORIA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'AFIM ASESORIA','cif' => 'B-33908674','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '263','titulo' => 'AGESL','categoria' => '10','calle' => 'C/ CADIZ 19 - 4º IZQ','codigoPostal' => '39002','ciudad' => 'SANTANDER','provincia' => 'Cantabria','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'age@ceoecant.es','web' => 'www.agecantabria.com','personaDeContacto' => NULL,'telefono' => '942221792','fax' => '942221449','hotline' => NULL,'decripcion' => 'AGESL','longitud' => NULL,'latitud' => NULL,'pobacion' => 'cantabria','decripcionLarga' => 'AGESL','cif' => 'B-39353073','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '264','titulo' => 'AGROFORESTAL CANDAL, S.L.','categoria' => '10','calle' => 'C/ SUMIO, 11 - VALLE DE BARCIA','codigoPostal' => '15175','ciudad' => 'CARRAL','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'joseluiscandal@hotmail.com','web' => 'www.agroforestalcandal.com','personaDeContacto' => NULL,'telefono' => '628703388','fax' => '981607593','hotline' => NULL,'decripcion' => 'AGROFORESTAL CANDAL, S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'AGROFORESTAL CANDAL, S.L.','cif' => 'B-15978307','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '265','titulo' => 'AIS NORTE','categoria' => '10','calle' => 'Rda Outeiro 238 1 izq y centro','codigoPostal' => '15010','ciudad' => 'A Coruña','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'lasesoria@mundo-r.com','web' => 'www.aisnorte06.es','personaDeContacto' => NULL,'telefono' => '881896858','fax' => '0','hotline' => NULL,'decripcion' => 'AIS NORTE','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'AIS NORTE','cif' => 'B-70057120','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '266','titulo' => 'AKROS ASESORIA','categoria' => '10','calle' => 'González Besada, 46 bajo','codigoPostal' => '33007','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'akros.asesoria@gmail.com','web' => 'www.akrosasesoria.es','personaDeContacto' => NULL,'telefono' => '984280774','fax' => '984280776','hotline' => NULL,'decripcion' => 'AKROS ASESORIA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'AKROS ASESORIA','cif' => 'B-74282112','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '267','titulo' => 'AL CONSULTORES','categoria' => '10','calle' => 'Alcalde Peñamaría de Llano, 3 Bajo','codigoPostal' => '15010','ciudad' => 'LA CORUÑA','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'martin@consultoresal.es','web' => 'www.consultoresal.es.pyme','personaDeContacto' => NULL,'telefono' => '981277277','fax' => '981277261','hotline' => NULL,'decripcion' => 'AL CONSULTORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'AL CONSULTORES','cif' => 'B-15493307','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '268','titulo' => 'ALGONZ ASESORÍA','categoria' => '10','calle' => 'C/ Les Cigarreres 21, 1º B','codigoPostal' => '33211','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'angeles@algonz.es','web' => 'www.algonz.es.pyme','personaDeContacto' => NULL,'telefono' => '985149836','fax' => '985164890','hotline' => NULL,'decripcion' => 'ALGONZ ASESORÍA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ALGONZ ASESORÍA','cif' => '53645022-Y','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '269','titulo' => 'ARBAL ASESORES','categoria' => '10','calle' => 'C/ Marqués de San Esteban nº 60 1º Dcha.','codigoPostal' => '33206','ciudad' => 'GIJÓN','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'arbal@telefonica.net','web' => 'www.arbalasesores.es','personaDeContacto' => NULL,'telefono' => '985343449','fax' => '985341943','hotline' => NULL,'decripcion' => 'ARBAL ASESORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ARBAL ASESORES','cif' => 'B-33858929','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '270','titulo' => 'ASEGRAIN','categoria' => '10','calle' => 'PLAZA INÉS DE OSORIO Nº6 - 1º A','codigoPostal' => '34005','ciudad' => 'PALENCIA','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'miriamrobla@asegrain.com','web' => 'www.asegrain.es','personaDeContacto' => NULL,'telefono' => '987007240','fax' => '987007240','hotline' => NULL,'decripcion' => 'ASEGRAIN','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'ASEGRAIN','cif' => 'B-34249516','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '271','titulo' => 'ASERCANT CONSULTING','categoria' => '10','calle' => 'C/ Luis Martínez nº 21','codigoPostal' => '39005','ciudad' => 'SANTANDER','provincia' => 'Cantabria','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'info@asercant.es','web' => 'www.asesoriafacil.net','personaDeContacto' => NULL,'telefono' => '692007017','fax' => '942272806','hotline' => NULL,'decripcion' => 'ASERCANT CONSULTING','longitud' => NULL,'latitud' => NULL,'pobacion' => 'cantabria','decripcionLarga' => 'ASERCANT CONSULTING','cif' => '20211706-L','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '272','titulo' => 'ASERVEGA','categoria' => '10','calle' => 'CARRETERA MEDINA, 5','codigoPostal' => '47410','ciudad' => 'OLMEDO','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'ralsastre@telefonica.net','web' => 'www.aservega.es','personaDeContacto' => NULL,'telefono' => '983601188','fax' => '983601188','hotline' => NULL,'decripcion' => 'ASERVEGA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'ASERVEGA','cif' => '12378783-E','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '273','titulo' => 'ASESNORA','categoria' => '10','calle' => 'C/ FLORENCIO RODRIGUEZ, 7 - 1º B','codigoPostal' => '33510','ciudad' => 'POLA DE SIERO','provincia' => 'Asturias - Siero','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesnora@gmail.com','web' => 'www.asesoriaasesnora.com','personaDeContacto' => NULL,'telefono' => '985722263','fax' => '985722263','hotline' => NULL,'decripcion' => 'ASESNORA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESNORA','cif' => 'B-74161613','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '274','titulo' => 'Asesoría A. Valdés - I. Fdez. S.L.','categoria' => '10','calle' => 'Plaza de Argüelles, 46 - 3º A','codigoPostal' => '33510','ciudad' => 'POLA DE SIERO','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'valdesfernandez@telefonica.net','web' => 'www.asesoriavaldesfernandez.com.pyme','personaDeContacto' => NULL,'telefono' => '985721888','fax' => '985721188','hotline' => NULL,'decripcion' => 'Asesoría A. Valdés - I. Fdez. S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'Asesoría A. Valdés - I. Fdez. S.L.','cif' => 'B-33527870','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '275','titulo' => 'ASESORIA AFISDEL SL','categoria' => '10','calle' => 'C/ GIL DE JAZ  4- 1º D','codigoPostal' => '33004','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesoriaafisdel@yahoo.es','web' => 'www.afisdel.es','personaDeContacto' => NULL,'telefono' => '985257604','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORIA AFISDEL SL','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORIA AFISDEL SL','cif' => 'B-33504838','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '276','titulo' => 'ASESORIA ARGO, C.B.','categoria' => '10','calle' => 'TRAV. SAN ANTONIO, 4 - BAJO','codigoPostal' => '33120','ciudad' => 'PRAVIA','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'capilarona@terra.es','web' => 'www.inmobiliariaargo.com','personaDeContacto' => NULL,'telefono' => '985821946','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORIA ARGO, C.B.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORIA ARGO, C.B.','cif' => 'E-33078320','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '277','titulo' => 'ASESORIA AUCOSA','categoria' => '10','calle' => 'Avda.de la Costa,41 entlo dcha','codigoPostal' => '33201','ciudad' => 'Gijón','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'aucosa1@asesoriaaucosa.com','web' => 'www.asesoriaaucosa.com.pyme','personaDeContacto' => NULL,'telefono' => '985341844','fax' => '985342392','hotline' => NULL,'decripcion' => 'ASESORIA AUCOSA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORIA AUCOSA','cif' => 'B-33692468','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '278','titulo' => 'ASESORÍA CANALES','categoria' => '10','calle' => 'C/ VIRGEN DEL CAMPO, 15 - BAJO','codigoPostal' => '39500','ciudad' => 'CABEZON DE LA SAL','provincia' => 'Cantabria','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesoriacanales@gmail.com','web' => 'www.asesoriacanalescantabria.es','personaDeContacto' => NULL,'telefono' => '942702442','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORÍA CANALES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'cantabria','decripcionLarga' => 'ASESORÍA CANALES','cif' => '13896551-C','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '279','titulo' => 'ASESORÍA DAMIÁN VALLINA','categoria' => '10','calle' => 'C/ Doctor Casal nº 12 - 4º B','codigoPostal' => '33001','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'marco@damianvallina.com','web' => 'www.damianvallina.com.pyme','personaDeContacto' => NULL,'telefono' => '985224960','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORÍA DAMIÁN VALLINA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORÍA DAMIÁN VALLINA','cif' => 'B-33560475','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '280','titulo' => 'ASESORIA DE LA TORRE','categoria' => '10','calle' => 'C/ Pelayo, 8 - 2º B','codigoPostal' => '49014','ciudad' => 'ZAMORA','provincia' => 'Zamora','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'torrepastor@economistas.org','web' => 'www.asesoriadelatorre.es','personaDeContacto' => NULL,'telefono' => '980532345','fax' => '980160797','hotline' => NULL,'decripcion' => 'ASESORIA DE LA TORRE','longitud' => NULL,'latitud' => NULL,'pobacion' => 'zamora','decripcionLarga' => 'ASESORIA DE LA TORRE','cif' => 'B-49258452','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '281','titulo' => 'ASESORIA DISOGON','categoria' => '10','calle' => 'C/ MARQUÉS DE ROBRERO, 15 -  1ºC','codigoPostal' => '39740','ciudad' => 'SANTOÑA','provincia' => 'Cantabria','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'santalo3@yahoo.es','web' => 'www.disogon.com','personaDeContacto' => NULL,'telefono' => '942671968','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORIA DISOGON','longitud' => NULL,'latitud' => NULL,'pobacion' => 'cantabria','decripcionLarga' => 'ASESORIA DISOGON','cif' => 'J-39721154','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '282','titulo' => 'ASESORIA EMAR','categoria' => '10','calle' => 'PLZ LA CRUZ, Nº13 1ºB','codigoPostal' => '33180','ciudad' => 'NOREÑA','provincia' => 'Asturias - Siero','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'evaarboleya@hotmail.com','web' => 'www.asesoriaemar.com','personaDeContacto' => NULL,'telefono' => '985744540','fax' => '985744540','hotline' => NULL,'decripcion' => 'ASESORIA EMAR','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORIA EMAR','cif' => '52610151-C','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '283','titulo' => 'ASESORIA FERCAS, S.L.','categoria' => '10','calle' => 'AVDA. REP. ARGENTINA 11- 1º','codigoPostal' => '24004','ciudad' => 'León','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'angel@asesoriafercas.es','web' => 'www.asesoriafercas.es','personaDeContacto' => NULL,'telefono' => '987205111','fax' => '987213607','hotline' => NULL,'decripcion' => 'ASESORIA FERCAS, S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'ASESORIA FERCAS, S.L.','cif' => 'B-24031122','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '284','titulo' => 'ASESORÍA GERMÁN MONREAL','categoria' => '10','calle' => 'C/ Duque de la Victoria, 14 - 3º B','codigoPostal' => '47001','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'gmonreal@infonegocio.com','web' => 'www.gmonreal.es','personaDeContacto' => NULL,'telefono' => '983213594','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORÍA GERMÁN MONREAL','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'ASESORÍA GERMÁN MONREAL','cif' => 'B-47405279','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '285','titulo' => 'ASESORÍA GUTIÉRREZ & ZAPICO','categoria' => '10','calle' => 'C/ Gil de Jaz, 7 - 2º D','codigoPostal' => '33004','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'pguti@telecable.es','web' => 'www.asesoriagutierrezyzapico.com','personaDeContacto' => NULL,'telefono' => '985234675','fax' => '985084675','hotline' => NULL,'decripcion' => 'ASESORÍA GUTIÉRREZ & ZAPICO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORÍA GUTIÉRREZ & ZAPICO','cif' => '09399895-W','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '286','titulo' => 'ASESORÍA JOVELLANOS','categoria' => '10','calle' => 'C/ Saavedra, 4 - Of. 20','codigoPostal' => '33208','ciudad' => 'GIJÓN','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'aj1@asesoriasjovellanos.com','web' => 'www.asesoriasjovellanos.es','personaDeContacto' => NULL,'telefono' => '985140582','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORÍA JOVELLANOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORÍA JOVELLANOS','cif' => 'B-33901588','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '287','titulo' => 'ASESORIA LA ARENA','categoria' => '10','calle' => 'Manso, 14 - 1º A','codigoPostal' => '33203','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'laarenaasesores@telecable.es','web' => 'www.laarenaasesores.es','personaDeContacto' => NULL,'telefono' => '985374528','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORIA LA ARENA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORIA LA ARENA','cif' => 'B-33917915','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '288','titulo' => 'ASESORÍA LAFISE','categoria' => '10','calle' => 'C/ Fruela, 14- 1º F','codigoPostal' => '33007','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'lafise@infonegocio.com','web' => 'www.asesorialafise.com','personaDeContacto' => NULL,'telefono' => '985222892','fax' => '985223487','hotline' => NULL,'decripcion' => 'ASESORÍA LAFISE','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORÍA LAFISE','cif' => 'B-33589664','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '289','titulo' => 'ASESORÍA ORVIZ','categoria' => '10','calle' => 'PL. MANUEL URÍA, Nº 11 -1º B','codigoPostal' => '33520','ciudad' => 'NAVA','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'jorviz@orvizloredo.net','web' => 'www.asesoriaorviz.com','personaDeContacto' => NULL,'telefono' => '985717243','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORÍA ORVIZ','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORÍA ORVIZ','cif' => '09361048-W','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '291','titulo' => 'ASESORÍA PUMARÍN','categoria' => '10','calle' => 'C/ Evaristo Valle nº 3 - 1º L','codigoPostal' => '33011','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesoria_pumarin@yahoo.es','web' => 'www.asesoriapumarin.es.pyme','personaDeContacto' => NULL,'telefono' => '985298186','fax' => '985115980','hotline' => NULL,'decripcion' => 'ASESORÍA PUMARÍN','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORÍA PUMARÍN','cif' => 'B-33419029','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '293','titulo' => 'ASESORIA QUESADA','categoria' => '10','calle' => 'Plaza Alfonso X El Sabio, 14- 1º D','codigoPostal' => '33630','ciudad' => 'POLA DE LENA','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'correo@asesoriaquesada.com','web' => 'www.asesoriaquesada.es','personaDeContacto' => NULL,'telefono' => '985490344','fax' => '985497009','hotline' => NULL,'decripcion' => 'ASESORIA QUESADA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORIA QUESADA','cif' => '11067308-F','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '294','titulo' => 'ASESORIA SANTA CRUZ','categoria' => '10','calle' => 'C/ GONZÁLEZ DEL VALLE, 7 - 5ºG','codigoPostal' => '33003','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'santacruz@telecable.es','web' => 'www.santacruzasesoria.es','personaDeContacto' => NULL,'telefono' => '985235192','fax' => '0','hotline' => NULL,'decripcion' => 'ASESORIA SANTA CRUZ','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ASESORIA SANTA CRUZ','cif' => 'B-33406034','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '295','titulo' => 'Assertor','categoria' => '10','calle' => 'C/ CORRIDA 19 - 4º IZQDA.','codigoPostal' => '33206','ciudad' => 'Gijon','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => '0','web' => 'www.assertor.es','personaDeContacto' => NULL,'telefono' => '984394255','fax' => '984394237','hotline' => NULL,'decripcion' => 'Assertor','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'Assertor','cif' => 'B-33889312','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '296','titulo' => 'ASTELA','categoria' => '10','calle' => 'C/ JUANA DE VEGA,  29-31 - 4º A','codigoPostal' => '15004','ciudad' => 'A CORUÑA','provincia' => 'La Coruña / A Coruña','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'amaliav@astela.es','web' => 'www.astela.org','personaDeContacto' => NULL,'telefono' => '981224557','fax' => '0','hotline' => NULL,'decripcion' => 'ASTELA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'acoruña','decripcionLarga' => 'ASTELA','cif' => 'A-15052970','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '297','titulo' => 'BUFETE Y GESTIÓN ASESORÍA','categoria' => '10','calle' => 'C/ Roa de la Vega nº 14, Entrep. Dcha','codigoPostal' => '24002','ciudad' => 'LEÓN','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesoria@bufeteygestion.com','web' => 'www.bufeteygestion.com.pyme','personaDeContacto' => NULL,'telefono' => '987239500','fax' => '0','hotline' => NULL,'decripcion' => 'BUFETE Y GESTIÓN ASESORÍA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'BUFETE Y GESTIÓN ASESORÍA','cif' => 'B-24322901','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '298','titulo' => 'C. A. C. Asesores, S. L.','categoria' => '10','calle' => 'C/ MURO 23, 4º IZQDA.','codigoPostal' => '47004','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'cac@cac-asesores.es','web' => 'www.cac-asesores.es','personaDeContacto' => NULL,'telefono' => '983373777','fax' => '0','hotline' => NULL,'decripcion' => 'C. A. C. Asesores, S. L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'C. A. C. Asesores, S. L.','cif' => 'B-47436381','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '299','titulo' => 'COFESA CONSULTING','categoria' => '10','calle' => 'C/ CALVO SOTELO, 16 -1º IZDA','codigoPostal' => '39002','ciudad' => 'SANTANDER','provincia' => 'Cantabria','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesores@cofesa.jazztel.es','web' => 'www.cofesaasesores.es','personaDeContacto' => NULL,'telefono' => '942314292','fax' => '942314713','hotline' => NULL,'decripcion' => 'COFESA CONSULTING','longitud' => NULL,'latitud' => NULL,'pobacion' => 'cantabria','decripcionLarga' => 'COFESA CONSULTING','cif' => 'B-39564653','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '300','titulo' => 'CONSULTORES RENTA MAS, S.L.','categoria' => '10','calle' => 'Avda. Requejo, 29 entreplanta','codigoPostal' => '49012','ciudad' => 'ZAMORA','provincia' => 'Zamora','comunidadAutonoma' => '','pais' => 'España','email' => 'rentamas@gmail.com','web' => 'http://www.rentamas.es','personaDeContacto' => NULL,'telefono' => '661567410','fax' => '980525716','hotline' => NULL,'decripcion' => '<p>CONSULTORES RENTA MAS, S.L.</p>','longitud' => '','latitud' => '','pobacion' => 'zamora','decripcionLarga' => '<p>CONSULTORES RENTA MAS, S.L.</p>','cif' => 'B-49242423','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '301','titulo' => 'CONTA KING ASESORÍA','categoria' => '10','calle' => 'C/ San Francisco, 13 - 9º B','codigoPostal' => '33003','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'direccion@contaking.com','web' => 'www.contaking.com.pyme','personaDeContacto' => NULL,'telefono' => '984109972','fax' => '984189659','hotline' => NULL,'decripcion' => 'CONTA KING ASESORÍA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'CONTA KING ASESORÍA','cif' => 'B-74160334','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '302','titulo' => 'DAPENA ABOGADOS','categoria' => '10','calle' => 'C/ Pelayo, 2 - 6º A y 9º B','codigoPostal' => '33205','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'javier@juandapenaabogados.com','web' => 'www.abogadosdapena.es','personaDeContacto' => NULL,'telefono' => '985358697','fax' => '0','hotline' => NULL,'decripcion' => 'DAPENA ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'DAPENA ABOGADOS','cif' => 'E-33933367','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '303','titulo' => 'DOMSA','categoria' => '10','calle' => 'C/ Moisés de León nº 12 - 1º','codigoPostal' => '24006','ciudad' => 'LEON','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'domingo@asesoriadomsa.com','web' => 'www.sansei.es','personaDeContacto' => NULL,'telefono' => '987215751','fax' => '987215751','hotline' => NULL,'decripcion' => 'DOMSA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'DOMSA','cif' => 'B-24430951','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '304','titulo' => 'E.P.V','categoria' => '10','calle' => 'CADIZ, 10 - 1ºC','codigoPostal' => '39002','ciudad' => 'SANTANDER','provincia' => 'Cantabria','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesores@epvnorte.com','web' => 'www.epvnorte.es','personaDeContacto' => NULL,'telefono' => '942367070','fax' => '942367170','hotline' => NULL,'decripcion' => 'E.P.V','longitud' => NULL,'latitud' => NULL,'pobacion' => 'cantabria','decripcionLarga' => 'E.P.V','cif' => 'A-39402060','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '305','titulo' => 'EUROLID CONSULTORES','categoria' => '10','calle' => 'CARRETERA RUEDA , Nº 52, 1º B','codigoPostal' => '47008','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'juanarranz@eurolid.e.telefonica.net','web' => 'www.eurolidconsultores.es','personaDeContacto' => NULL,'telefono' => '983319010','fax' => '983237849','hotline' => NULL,'decripcion' => 'EUROLID CONSULTORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'EUROLID CONSULTORES','cif' => 'B-47418918','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '306','titulo' => 'EZEQUIEL GREGORIO MARTÍN','categoria' => '10','calle' => 'JUAN DE JUNI-8 ENTRP.','codigoPostal' => '47006','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'ezequiel_gregorio@yahoo.es','web' => 'www.ezequielgregorio.es','personaDeContacto' => NULL,'telefono' => '983358406','fax' => '983335422','hotline' => NULL,'decripcion' => 'EZEQUIEL GREGORIO MARTÍN','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'EZEQUIEL GREGORIO MARTÍN','cif' => '11709137-K','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '307','titulo' => 'finiscont','categoria' => '10','calle' => 'c/ martinez marina nº3 1ºC','codigoPostal' => '33009','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesoria@finiscont.com','web' => 'www.finiscont.com.pyme','personaDeContacto' => NULL,'telefono' => '985227747','fax' => '0','hotline' => NULL,'decripcion' => 'finiscont','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'finiscont','cif' => 'B-33523382','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '309','titulo' => 'FORCEAS','categoria' => '10','calle' => 'C/ INVENTOR DE LA CIERVA, 26 - 1º','codigoPostal' => '33930','ciudad' => 'LANGREO','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'forceas@gmail.com','web' => 'www.forceas.es','personaDeContacto' => NULL,'telefono' => '666097938','fax' => '985676710','hotline' => NULL,'decripcion' => 'FORCEAS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'FORCEAS','cif' => '32881547-B','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '310','titulo' => 'FRANCISCO JAVIER GUERRERO','categoria' => '10','calle' => 'Rosalía de Castro 6 3ºB','codigoPostal' => '24400','ciudad' => 'Ponferrada','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'guerrerosuiza@hotmail.com','web' => 'www.ghgabinete.es','personaDeContacto' => NULL,'telefono' => '987088436','fax' => '675341153','hotline' => NULL,'decripcion' => 'FRANCISCO JAVIER GUERRERO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'FRANCISCO JAVIER GUERRERO','cif' => '71529678-T','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '313','titulo' => 'FULL CONTACT','categoria' => '10','calle' => 'C/ PADRE ALLER,  7 - 6ºB','codigoPostal' => '33012','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'jmfeliz@fullcontact-int.com','web' => 'www.fullcontact-int.net','personaDeContacto' => NULL,'telefono' => '985232048','fax' => '0','hotline' => NULL,'decripcion' => 'FULL CONTACT','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'FULL CONTACT','cif' => 'J-74282658','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '314','titulo' => 'GERMAN ESTEBANEZ MOVILLA','categoria' => '10','calle' => 'G.V SAN MARCOS, 35 3º IZQ','codigoPostal' => '24001','ciudad' => 'LEON','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'estebanez87@telefonica.net','web' => 'www.germanestebanezabogado.com','personaDeContacto' => NULL,'telefono' => '987276047','fax' => '0','hotline' => NULL,'decripcion' => 'GERMAN ESTEBANEZ MOVILLA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'GERMAN ESTEBANEZ MOVILLA','cif' => '11953449-G','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '315','titulo' => 'GESFASE','categoria' => '10','calle' => 'C/ CARREÑO MIRANDA, 43 - 1º','codigoPostal' => '33600','ciudad' => 'MIERES','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'aspuente@telecable.es','web' => 'www.gesfase.es','personaDeContacto' => NULL,'telefono' => '630573784','fax' => '0','hotline' => NULL,'decripcion' => 'GESFASE','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'GESFASE','cif' => '10823970-D','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '316','titulo' => 'GESPER ASESORES','categoria' => '10','calle' => 'C/ Anselmo Cifuentes nº 11 Entreplanta Dcha.','codigoPostal' => '33205','ciudad' => 'GIJÓN','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'rubend@gesperasesores.com','web' => 'www.asesoresgesper.es','personaDeContacto' => NULL,'telefono' => '985349456','fax' => '985346869','hotline' => NULL,'decripcion' => 'GESPER ASESORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'GESPER ASESORES','cif' => 'B-33751504','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '317','titulo' => 'GESTORÍA MIRALLES','categoria' => '10','calle' => 'C/ Calvo Sotelo nº 21 - Entlo. C','codigoPostal' => '33007','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'gestoria_miralles@asturias.com','web' => 'www.gestoriamiralles.com.pyme','personaDeContacto' => NULL,'telefono' => '985237168','fax' => '0','hotline' => NULL,'decripcion' => 'GESTORÍA MIRALLES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'GESTORÍA MIRALLES','cif' => '09402683-F','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '318','titulo' => 'GRUPO MULTIGESTION','categoria' => '10','calle' => 'Domingo García de la Fuente 24','codigoPostal' => '33205','ciudad' => 'Gijón','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'multigestion@telecable.es','web' => 'www.grupomultigestionasturias.com','personaDeContacto' => NULL,'telefono' => '984490216','fax' => '0','hotline' => NULL,'decripcion' => 'GRUPO MULTIGESTION','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'GRUPO MULTIGESTION','cif' => '10848002-Y','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '319','titulo' => 'GYP BROKER C.B.','categoria' => '10','calle' => 'Av. Aldebaran, 27 BJ (Urb. Aldebaran','codigoPostal' => '37900','ciudad' => 'SANTA MARTA DE TORMES','provincia' => 'Salamanca','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'gyp_brokerc.b@hotmail.com','web' => 'www.gypbroker.com','personaDeContacto' => NULL,'telefono' => '677184681','fax' => '0','hotline' => NULL,'decripcion' => 'GYP BROKER C.B.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'salamanca','decripcionLarga' => 'GYP BROKER C.B.','cif' => 'E-37470838','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '320','titulo' => 'HERTODEZA ASESORIA Y AUDITORIA, S.L.','categoria' => '10','calle' => 'C/ CORTINAS DE SAN MIGUEL,  6 - 1º D','codigoPostal' => '49013','ciudad' => 'ZAMORA','provincia' => 'Zamora','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'hertodeza@hertodeza.onored.com','web' => 'www.hertodeza.com','personaDeContacto' => NULL,'telefono' => '980534621','fax' => '0','hotline' => NULL,'decripcion' => 'HERTODEZA ASESORIA Y AUDITORIA, S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'zamora','decripcionLarga' => 'HERTODEZA ASESORIA Y AUDITORIA, S.L.','cif' => 'B-49165343','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '321','titulo' => 'HORIZONTE ASESORES','categoria' => '10','calle' => 'C/ BRASIL, 14 - BAJO','codigoPostal' => '33213','ciudad' => 'GIJON','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'horizonteana@greencom.net','web' => 'www.horizonteasesores.es','personaDeContacto' => NULL,'telefono' => '985301796','fax' => '985309639','hotline' => NULL,'decripcion' => 'HORIZONTE ASESORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'HORIZONTE ASESORES','cif' => '10858558-M','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '322','titulo' => 'Ignacio de la Cueva López Chaves','categoria' => '10','calle' => 'C/ Toro nº 78 1º H','codigoPostal' => '37002','ciudad' => 'SALAMANCA','provincia' => 'Salamanca','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'idelacueva@economistas.org','web' => 'www.asesoriaignaciodelacueva.es','personaDeContacto' => NULL,'telefono' => '923211872','fax' => '0','hotline' => NULL,'decripcion' => 'Ignacio de la Cueva López Chaves','longitud' => NULL,'latitud' => NULL,'pobacion' => 'salamanca','decripcionLarga' => 'Ignacio de la Cueva López Chaves','cif' => '07823519-T','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '323','titulo' => 'IGSEZA CONSULTORES S.L.','categoria' => '10','calle' => 'Diego de Losada, 8 - Entreplanta A','codigoPostal' => '49018','ciudad' => 'ZAMORA','provincia' => 'Zamora','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'igseza@igseza.e.telefonica.net','web' => 'www.igseza.com','personaDeContacto' => NULL,'telefono' => '980557419','fax' => '980557093','hotline' => NULL,'decripcion' => 'IGSEZA CONSULTORES S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'zamora','decripcionLarga' => 'IGSEZA CONSULTORES S.L.','cif' => 'B-49203102','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '326','titulo' => 'IMC ASESORES','categoria' => '10','calle' => 'PALACIO VALDES, 4 - 2ºE','codigoPostal' => '33002','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asturvelasco@hotmail.com','web' => 'www.imcasesores.net','personaDeContacto' => NULL,'telefono' => '985221852','fax' => '984051291','hotline' => NULL,'decripcion' => 'IMC ASESORES','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'IMC ASESORES','cif' => 'E-33573916','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '327','titulo' => 'INFISCO','categoria' => '10','calle' => 'C/ Santa Rosa nº 3, 1º','codigoPostal' => '49600','ciudad' => 'BENAVENTE','provincia' => 'Zamora','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'infisco@wanadoo.es','web' => 'www.infisco.es','personaDeContacto' => NULL,'telefono' => '980636638','fax' => '980637833','hotline' => NULL,'decripcion' => 'INFISCO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'zamora','decripcionLarga' => 'INFISCO','cif' => 'B-49254881','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '328','titulo' => 'INYTRAM GEOLOGOS CONSULTORES, S.L.','categoria' => '10','calle' => 'C/ Marqués de San Esteban, 60 - Entlo. Izda.','codigoPostal' => '33206','ciudad' => 'GIJÓN','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'inytram@teleline.es','web' => 'www.inytramgeologos.com','personaDeContacto' => NULL,'telefono' => '985352895','fax' => '985348017','hotline' => NULL,'decripcion' => 'INYTRAM GEOLOGOS CONSULTORES, S.L.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'INYTRAM GEOLOGOS CONSULTORES, S.L.','cif' => 'B-33847302','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '329','titulo' => 'JESUS SANCHEZ Y ASOCIADOS','categoria' => '10','calle' => 'C/ Abedul nº 1 Bajo','codigoPostal' => '47009','ciudad' => 'Valladolid','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'js.adp2025@gmail.com','web' => 'www.adp2025.com','personaDeContacto' => NULL,'telefono' => '983378438','fax' => '983356082','hotline' => NULL,'decripcion' => 'JESUS SANCHEZ Y ASOCIADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'JESUS SANCHEZ Y ASOCIADOS','cif' => 'B-47478904','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '330','titulo' => 'JJG Asesores','categoria' => '10','calle' => 'C/ Rector Lucena 20 - 5º G','codigoPostal' => '37002','ciudad' => 'SALAMANCA','provincia' => 'Salamanca','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'julioblazquez@telefonica.net','web' => 'www.jjgasesores.com.pyme','personaDeContacto' => NULL,'telefono' => '923138362','fax' => '0','hotline' => NULL,'decripcion' => 'JJG Asesores','longitud' => NULL,'latitud' => NULL,'pobacion' => 'salamanca','decripcionLarga' => 'JJG Asesores','cif' => 'B-37419652','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '331','titulo' => 'JOJUSA','categoria' => '10','calle' => 'CIENFUEGOS, 5','codigoPostal' => '33205','ciudad' => 'GIJÓN','provincia' => 'Asturias - Gijón','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'jojusa@telecable.es','web' => 'www.asesoriajojusa.es','personaDeContacto' => NULL,'telefono' => '984393753','fax' => '0','hotline' => NULL,'decripcion' => 'JOJUSA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'JOJUSA','cif' => 'B-33950650','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '332','titulo' => 'JUAN GALAN ASESORÍA LABORAL','categoria' => '10','calle' => 'González del Valle, nº 3, 1º b','codigoPostal' => '33003','ciudad' => 'Oviedo','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'info@asesoriagalan.com','web' => 'www.asesoriagalan.com.pyme','personaDeContacto' => NULL,'telefono' => '985223160','fax' => '985223160','hotline' => NULL,'decripcion' => 'JUAN GALAN ASESORÍA LABORAL','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'JUAN GALAN ASESORÍA LABORAL','cif' => '09435988-P','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '333','titulo' => 'JUAN SIMÓN','categoria' => '10','calle' => 'C/ Santiago nº 15 - 2º Centro','codigoPostal' => '47001','ciudad' => 'VALLADOLID','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'juan@juansimon.e.telefonica.net','web' => 'www.juansimon.es','personaDeContacto' => NULL,'telefono' => '983341455','fax' => '983341455','hotline' => NULL,'decripcion' => 'JUAN SIMÓN','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'JUAN SIMÓN','cif' => '12218712-P','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '334','titulo' => 'LUENGO Y ALBA','categoria' => '10','calle' => 'C/ Uría nº 60, 1º F','codigoPostal' => '33003','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'luengoyalba@telefonica.net','web' => 'www.luengoyalba.com','personaDeContacto' => NULL,'telefono' => '985218231','fax' => '985218231','hotline' => NULL,'decripcion' => 'LUENGO Y ALBA','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'LUENGO Y ALBA','cif' => 'B-33433673','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '335','titulo' => 'MANJÓN ASESOR','categoria' => '10','calle' => 'Avda. Cervantes, 6 - 5º B','codigoPostal' => '33402','ciudad' => 'AVILES','provincia' => 'Asturias - Avilés','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'smanjon@telecable.es','web' => 'www.manjonasesor.es','personaDeContacto' => NULL,'telefono' => '629280770','fax' => '0','hotline' => NULL,'decripcion' => 'MANJÓN ASESOR','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'MANJÓN ASESOR','cif' => '34919570-G','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '336','titulo' => 'MORALES Y OBISPO','categoria' => '10','calle' => 'RAMÓN CALABOZO 3 BAJO','codigoPostal' => '24009','ciudad' => 'LEÓN','provincia' => 'León','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'morobi@empresas.retecal.es','web' => 'www.morobi.org','personaDeContacto' => NULL,'telefono' => '987218658','fax' => '987218678','hotline' => NULL,'decripcion' => 'MORALES Y OBISPO','longitud' => NULL,'latitud' => NULL,'pobacion' => 'leon','decripcionLarga' => 'MORALES Y OBISPO','cif' => 'B-24415374','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '337','titulo' => 'PABLO DÍAZ MATOS ABOGADOS','categoria' => '10','calle' => 'Gil de Jaz, 3 - 5º B','codigoPostal' => '33004','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'p.matos@fade.es','web' => 'www.diazmatosabogados.com','personaDeContacto' => NULL,'telefono' => '985276620','fax' => '985272747','hotline' => NULL,'decripcion' => 'PABLO DÍAZ MATOS ABOGADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'PABLO DÍAZ MATOS ABOGADOS','cif' => '10472890-R','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '338','titulo' => 'PORRON Y ASOCIADOS','categoria' => '10','calle' => 'C/ La Regenta nº 1, Bajo 2','codigoPostal' => '33013','ciudad' => 'OVIEDO','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesores@porronyasociados.e.telefonica.net','web' => 'www.porronasesores.es','personaDeContacto' => NULL,'telefono' => '985115430','fax' => '985115431','hotline' => NULL,'decripcion' => 'PORRON Y ASOCIADOS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'PORRON Y ASOCIADOS','cif' => 'J-33571381','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '339','titulo' => 'PRIDA ADMINISTRACIÓN','categoria' => '10','calle' => 'C/ ALFONSO ARGUELLES 14 - 1º A','codigoPostal' => '33930','ciudad' => 'LA FELGUERA','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'prida.administracion@telefonica.net','web' => 'www.pridaadministracion.com','personaDeContacto' => NULL,'telefono' => '985682239','fax' => '0','hotline' => NULL,'decripcion' => 'PRIDA ADMINISTRACIÓN','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'PRIDA ADMINISTRACIÓN','cif' => '32867080-B','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '340','titulo' => 'R & R SERVICIOS EMPRESARIALES S.L','categoria' => '10','calle' => 'C/ CARDENAL MELLA  7 A, entreplanta','codigoPostal' => '49009','ciudad' => 'ZAMORA','provincia' => 'Zamora','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'asesoria@ramosyroman.com','web' => 'www.ramosyroman.es','personaDeContacto' => NULL,'telefono' => '980671052','fax' => '0','hotline' => NULL,'decripcion' => 'R & R SERVICIOS EMPRESARIALES S.L','longitud' => NULL,'latitud' => NULL,'pobacion' => 'zamora','decripcionLarga' => 'R & R SERVICIOS EMPRESARIALES S.L','cif' => 'B-49218183','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '341','titulo' => 'raisa credit','categoria' => '10','calle' => 'la lila nº3. 1ºB','codigoPostal' => '33009','ciudad' => 'Oviedo','provincia' => 'Asturias - Oviedo','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'tecnomix2001@yahoo.es','web' => 'www.raisacredit.es','personaDeContacto' => NULL,'telefono' => '985209122','fax' => '985218144','hotline' => NULL,'decripcion' => 'raisa credit','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'raisa credit','cif' => 'E-74085002','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '342','titulo' => 'ROMERO ASESORIA DE EMPRESAS','categoria' => '10','calle' => 'JOSE CUETO,4-1ºC','codigoPostal' => '33401','ciudad' => 'AVILES','provincia' => 'Asturias','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'romerosc@telecable.es','web' => 'www.romeroasesores.net','personaDeContacto' => NULL,'telefono' => '985569254','fax' => '984832197','hotline' => NULL,'decripcion' => 'ROMERO ASESORIA DE EMPRESAS','longitud' => NULL,'latitud' => NULL,'pobacion' => 'asturias','decripcionLarga' => 'ROMERO ASESORIA DE EMPRESAS','cif' => 'G-33374745','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '343','titulo' => 'Sanchez Martin Asesores','categoria' => '10','calle' => 'C/ Luna nº 1 Entreplanta A-5','codigoPostal' => '47007','ciudad' => 'Valladolid','provincia' => 'Valladolid','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'sanchezmartin@ono.com','web' => 'www.sanchezmartin.es','personaDeContacto' => NULL,'telefono' => '983378095','fax' => '983130803','hotline' => NULL,'decripcion' => 'Sanchez Martin Asesores','longitud' => NULL,'latitud' => NULL,'pobacion' => 'valladolid','decripcionLarga' => 'Sanchez Martin Asesores','cif' => 'B-47368980','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL),
			array('id' => '344','titulo' => 'SÁNCHEZ MOYA GESTIÓN EMPRESARIAL S.L.P.','categoria' => '10','calle' => 'C/ de arriba 14-16 - 1º A','codigoPostal' => '37002','ciudad' => 'SALAMANCA','provincia' => 'Salamanca','comunidadAutonoma' => NULL,'pais' => 'España','email' => 'anasmoya@hotmail.com','web' => 'www.asesoriasanchezmoya.es','personaDeContacto' => NULL,'telefono' => '923210718','fax' => '923210718','hotline' => NULL,'decripcion' => 'SÁNCHEZ MOYA GESTIÓN EMPRESARIAL S.L.P.','longitud' => NULL,'latitud' => NULL,'pobacion' => 'salamanca','decripcionLarga' => 'SÁNCHEZ MOYA GESTIÓN EMPRESARIAL S.L.P.','cif' => 'B-37292646','tipoFicha' => '3ficha_basica','perfilRedesSociales' => NULL)
		);
		foreach ($fichas as $ficha) {
			$entidad = new Ficha();
			$entidad->setId($ficha['id']);
			$entidad->setTitulo($ficha['titulo']);
			$entidad->setCategoria($manager->find('AppBundle:categoria', $ficha['categoria']));
			$entidad->setCalle($ficha['calle']);
			$entidad->setCodigoPostal($ficha['codigoPostal']);
			$entidad->setCiudad($ficha['ciudad']);
			$entidad->setProvincia($ficha['provincia']);
			$entidad->setComunidadAutonoma($ficha['comunidadAutonoma']);
			$entidad->setPais($ficha['comunidadAutonoma']);
			$entidad->setPais($ficha['pais']);
			$entidad->setEmail($ficha['email']);
			$entidad->setWeb($ficha['web']);
			$entidad->setPersonaDeContacto($ficha['personaDeContacto']);
			$entidad->setTelefono($ficha['telefono']);
			$entidad->setFax($ficha['fax']);
			$entidad->setHotline($ficha['hotline']);
			$entidad->setDescripcion($ficha['decripcion']);
			$entidad->setLongitud($ficha['longitud']);
			$entidad->setLatitud($ficha['latitud']);
			$entidad->setPoblacion($ficha['pobacion']);
			$entidad->setDescripcionLarga($ficha['decripcionLarga']);
			$entidad->setCif($ficha['cif']);
			$entidad->setTipoFicha($ficha['tipoFicha']);
			$entidad->setPerfilRedesSociales($ficha['perfilRedesSociales']);
			$manager->persist($entidad);
		}
		$manager->flush();
	}
}  
